apiVersion: v1
kind: Service
metadata:
  name: studio-server
  namespace: user-space-{{ .Values.bfl.username }}
spec:
  type: ExternalName
  externalName: studio-server.os-framework.svc.cluster.local
  ports:
    - protocol: TCP
      name: studio-server
      port: 8080
      targetPort: 8080