---
apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-proxy
  namespace: user-system-{{ .Values.bfl.username }}
spec:
  type: ClusterIP
  selector:
    app: systemserver
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
