apiVersion: v1
target: prebuilt
output:
  containers:
    - 
      name: ghcr.io/k8snetworkplumbingwg/multus-cni:v4.2.4

  binaries:
    - 
      id: cni-plugins
      name: cni-plugins-v1.6.2.tgz,pkg/cni/v1.6.2,
      amd64: https://github.com/beclab/plugins/releases/download/v1.6.2-olares1/cni-plugins-linux-amd64-v1.6.2-olares1.tgz
      arm64: https://github.com/beclab/plugins/releases/download/v1.6.2-olares1/cni-plugins-linux-arm64-v1.6.2-olares1.tgz
