package node

import (
	"log"

	"github.com/beclab/Olares/cli/cmd/config"
	"github.com/beclab/Olares/cli/pkg/common"
	"github.com/beclab/Olares/cli/pkg/pipelines"
	"github.com/spf13/cobra"
)

func NewCmdJoinNode() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "join",
		Short: "prepare this machine and join it to an Olares cluster",
		Args:  cobra.NoArgs,
		Run: func(cmd *cobra.Command, args []string) {
			if err := pipelines.JoinNodePipeline(cmd.Context()); err != nil {
				log.Fatalf("error: %v", err)
			}
		},
	}

	flagSetter := config.NewFlagSetterFor(cmd)
	config.AddBaseDirFlagBy(flagSetter)
	config.AddCDNServiceFlagBy(flagSetter)
	config.AddMasterHostFlagsBy(flagSetter)
	flagSetter.Add(common.FlagMasterAuthInfo, "", "", "Base64-encoded master connection information, as generated by 'node join-command'")
	flagSetter.Add(common.FlagNodeName, "", "", "Node name to join under, renaming this machine if needed; prompted for only if the current hostname cannot be used")
	flagSetter.Add(common.FlagRegistryMirrors, "r", "", "Extra container registry mirrors, separated by commas")
	flagSetter.Add(common.FlagReleaseID, "", "", "Set the specific release id of the release version")
	_ = cmd.Flags().MarkHidden(common.FlagMasterAuthInfo)
	_ = cmd.Flags().MarkHidden(common.FlagMasterSSHPassword)

	return cmd
}
