namespace: app-gateway
namespaceCreate: false
gateway:
  name: app-gateway
  gatewayClassName: olares-app-gateway
tls:
  enabled: true
envoyProxy:
  enabled: true
  name: app-gateway-envoy-proxy
  accessLog:
    enabled: true
envoy-gateway:
  deployment:
    envoyGateway:
      resources:
        limits:
          memory: 1024Mi
        requests:
          cpu: 100m
          memory: 256Mi
  autoscaling:
    enabled: false
  config:
    envoyGateway:
      gateway:
        controllerName: gateway.envoyproxy.io/gatewayclass-controller
      provider:
        type: Kubernetes
      logging:
        level:
          default: info
  createNamespace: false
  topologyInjector:
    enabled: true
  certgen:
    job:
      ttlSecondsAfterFinished: 30
