---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.bfl.username }}:download-provider-svc
  annotations:
    provider-registry-ref: user-system-{{ .Values.bfl.username }}/download
    provider-service-ref: download-svc.os-framework:8080
rules:
  - nonResourceURLs:
      - "/api/download*"
      - "/api/user/*"
      - "/api/system/*"
      - "/api/url/*"
    verbs: ["*"]
