apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.bfl.username }}:files-frontend-svc
  annotations:
    provider-registry-ref: user-system-{{ .Values.bfl.username }}/files
    provider-service-ref: files-service.os-framework:80
rules:
- nonResourceURLs: ["*"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.bfl.username }}:files-frontend-domain
  annotations:
    provider-registry-ref: {{ .Values.bfl.username }}/files
    provider-service-ref: files-service.os-framework:80
rules:
- nonResourceURLs: ["*"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.bfl.username }}:files-provider-svc
  annotations:
    provider-registry-ref: user-system-{{ .Values.bfl.username }}/files
    provider-service-ref: files-service.os-framework:80
rules:
- nonResourceURLs: ["/api/resources/*"]
  verbs: ["*"]


---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: user:{{ .Values.bfl.username }}:files
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.bfl.username }}:files-frontend-svc
subjects:
- kind: User
  name: {{ .Values.bfl.username }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: user:{{ .Values.bfl.username }}:files-frontend
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.bfl.username }}:files-frontend-domain
subjects:
- kind: User
  name: {{ .Values.bfl.username }}  