---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.bfl.username }}:settings-provider-svc
  annotations:
    provider-registry-ref: user-system-{{ .Values.bfl.username }}/settings
    provider-service-ref: settings-service.{{ .Release.Namespace }}
rules:
- nonResourceURLs: 
  - "/api/cloud/getNFTAddress"
  - "/api/account/"
  - "/api/backup/password"
  - "/api/account/retrieve"
  - "/api/account/all"
  - "/api/cookie/retrieve"
  - "/api/cookie"
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.bfl.username }}:edge-desktop-provider-svc
  annotations:
    provider-registry-ref: user-system-{{ .Values.bfl.username }}/edge-desktop
    provider-service-ref: edge-desktop.{{ .Release.Namespace }}
rules:
- nonResourceURLs: 
  - "/server/intent/send"
  - "/server/ai_message"
  verbs: ["*"]  
