export const ROUTE_NAME = {
	OVERVIEW: 'OVERVIEW',
	GPU_LIST: 'GPU_LIST',
	NETWORK_DETAIL: 'NETWORK_DETAIL',
	PHYSICAL_RESOURCE_DETAIL: 'PHYSICAL_RESOURCE_DETAIL',
	GPUS_DETAILS: 'GPUS_DETAILS',
	TASKS_DETAILS: 'TASKS_DETAILS',
	CPU_DETAIL: 'CPU_DETAIL',
	MEMORY_DETAIL: 'MEMORY_DETAIL',
	DISK_DETAIL: 'DISK_DETAIL',
	PODS_DETAIL: 'PODS_DETAIL',
	FAN_DETAIL: 'FAN_DETAIL'
};
