


apiVersion: v1
data:
  local_config.yaml: |
    server:
      apiServer:
        url: http://ks-apiserver.kubesphere-system
        wsUrl: ws://ks-apiserver.kubesphere-system
      http:
        hostname: localhost
        port: 8000
        static:
          production:
            /public: server/public
            /assets: dist/assets
            /dist: dist
      redis:
        port: 6379
        host: redis.kubesphere-system.svc
      redisTimeout: 5000
      sessionTimeout: 7200000
    client:
      version:
        kubesphere: v3.3.0
        kubernetes: v1.19.4
        openpitrix: v3.3.0
      enableKubeConfig: true
    defaultClusterName: default
kind: ConfigMap
metadata:
  name: ks-console-config
  namespace: {{ .Release.Namespace }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ks-console
    tier: frontend
    version: v3.3.0
    applications.app.bytetrade.io/author: bytetrade.io
    applications.app.bytetrade.io/name: console
    applications.app.bytetrade.io/owner: {{ .Values.username }}
  annotations:
    applications.app.bytetrade.io/icon: https://file.bttcdn.com/appstore/console/icon.png
    applications.app.bytetrade.io/title: Console
    applications.app.bytetrade.io/entrances: '[{"name":"console", "host":"ks-console", "port":80,"title":"Console"}]'
  name: ks-console
  namespace: {{ .Release.Namespace }}
spec:
  strategy:
    rollingUpdate:
      maxSurge: 0
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: ks-console
      tier: frontend
  template:
    metadata:
      labels:
        app: ks-console
        tier: frontend
        io.bytetrade.app: "true"
    spec:   
      containers:
      - image: kubesphere/ks-console:v3.3.0
        imagePullPolicy: IfNotPresent
        name: ks-console
        resources:
          limits:
            cpu: 1
            memory: 1024Mi
          requests:
            cpu: 20m
            memory: 100Mi
        volumeMounts:
        - mountPath: /opt/kubesphere/console/server/local_config.yaml
          name: ks-console-config
          subPath: local_config.yaml
        - mountPath: /etc/localtime
          name: host-time
          readOnly: true
        livenessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 15
          timeoutSeconds: 15
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 8
      serviceAccount: bytetrade-controller
      serviceAccountName: bytetrade-controller
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - ks-console
            namespaces:
            - {{ .Release.Namespace }}
      volumes:
      - configMap:
          defaultMode: 420
          name: ks-console-config
          items:
          - key: local_config.yaml
            path: local_config.yaml
        name: ks-console-config
      - hostPath:
          path: /etc/localtime
          type: ""
        name: host-time

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: ks-console
    tier: frontend
    version: v3.3.0
  name: ks-console
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: nginx
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: ks-console
    tier: frontend
  type: ClusterIP