---
apiVersion: v1
kind: Service
metadata:
  name: system-server
  namespace: user-system-{{ .Values.bfl.username }}
spec:
  type: ClusterIP
  selector:
    app: systemserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: api
    - protocol: TCP
      port: 28080
      targetPort: 28080
      name: proxy

---
apiVersion: v1
kind: Service
metadata:
  name: market
  namespace: user-system-{{ .Values.bfl.username }}
spec:
  type: ClusterIP
  selector:
    app: systemserver
  ports:
    - protocol: TCP
      port: 28080
      targetPort: 28080
