
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bytetrade-sys-ops
  namespace: user-system-{{ .Values.bfl.username }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: user-system-{{ .Values.bfl.username }}:bytetrade-sys-ops:nonresourceurl
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nonresourceurl-admin
subjects:
- kind: ServiceAccount
  name: bytetrade-sys-ops
  namespace: user-system-{{ .Values.bfl.username }}


---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: user-system-{{ .Values.bfl.username }}:bytetrade-sys-ops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sys-editor-role
subjects:
- kind: ServiceAccount
  name: bytetrade-sys-ops
  namespace: user-system-{{ .Values.bfl.username }}


---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: user-system-{{ .Values.bfl.username }}:bytetrade-sys-ops:rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rbac-proxy
subjects:
- kind: ServiceAccount
  name: bytetrade-sys-ops
  namespace: user-system-{{ .Values.bfl.username }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: system-server
  namespace: user-system-{{ .Values.bfl.username }}
  labels:
    app: systemserver
    applications.app.bytetrade.io/author: bytetrade.io
  annotations:
    applications.app.bytetrade.io/version: '0.0.1'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: systemserver
  template:
    metadata:
      labels:
        app: systemserver
      annotations:
{{ if .Values.telemetry }}
        instrumentation.opentelemetry.io/go-container-names: system-server
        instrumentation.opentelemetry.io/inject-go: olares-instrumentation
        instrumentation.opentelemetry.io/otel-go-auto-target-exe: /system-server
{{ end }}
    spec:
      serviceAccountName: bytetrade-sys-ops
      serviceAccount: bytetrade-sys-ops
      priorityClassName: "system-cluster-critical"
      containers:
      - name: system-server
        image: beclab/system-server:0.1.34
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        command:
        - /system-server
        - -v
        - "6"
        env:
        - name: MY_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: OWNER
          value: "{{ .Values.bfl.username }}"
