kind: Service
apiVersion: v1
metadata:
  name: gpu-scheduler
  namespace: gpu-system
spec:
  ports:
    - name: ws
      protocol: TCP
      port: 6000
      targetPort: 6000
  selector:
    name: gpu-scheduler
  type: ClusterIP
  internalTrafficPolicy: Local
