apiVersion: v1
kind: Service
metadata:
  name: app-gateway-data
  namespace: {{ include "app-gateway.namespace" . }}
  labels:
    app.kubernetes.io/name: app-gateway
    app.kubernetes.io/component: data-plane-stable
    applications.app.bytetrade.io/author: bytetrade.io
  annotations:
    gateway.olares.io/purpose: "Stable cluster-internal entrypoint to the EG data plane."
spec:
  type: ClusterIP
  selector:
    gateway.envoyproxy.io/owning-gateway-name: {{ .Values.gateway.name }}
    gateway.envoyproxy.io/owning-gateway-namespace: {{ include "app-gateway.namespace" . }}
    app.kubernetes.io/component: proxy
    app.kubernetes.io/managed-by: envoy-gateway
    app.kubernetes.io/name: envoy
  ports:
    - name: http
      port: 80
      targetPort: 10080
      protocol: TCP
    {{- if .Values.tls.enabled }}
    - name: https
      port: 443
      targetPort: 10443
      protocol: TCP
    {{- end }}
