
{{ $nats_rootpath := printf "%s%s" .Values.rootPath "/userdata/dbdata" }}
{{- $namespace := printf "%s" "os-platform" -}}
{{- $nats_secret := (lookup "v1" "Secret" $namespace "nats-secrets") -}}
{{- $nats_password := "" -}}
{{ if $nats_secret -}}
{{ $nats_password = (index $nats_secret "data" "nats_password") }}
{{ else -}}
{{ $nats_password = randAlpha 64 | b64enc }}
{{- end -}}

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nats-data-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: '50Gi'
  hostPath:
    path: '{{ $nats_rootpath }}/nats_data'
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Delete
  volumeMode: Filesystem
  storageClassName: nats-data-sc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nats-data-pvc
  namespace: {{ $namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: '50Gi'
  volumeMode: Filesystem
  volumeName: nats-data-pv
  storageClassName: nats-data-sc

---
apiVersion: v1
kind: Secret
metadata:
  name: nats-secrets
  namespace: {{ $namespace }}
type: Opaque
data:
  nats_password: {{ $nats_password }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nats
  namespace: {{ $namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nats-cm-sidecar
  namespace: {{ $namespace }}
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nats-cm-sidecar
  namespace: {{ $namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nats-cm-sidecar
subjects:
  - kind: ServiceAccount
    name: nats
    namespace: {{ $namespace }}
---
# Source: nats/templates/headless-service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: nats
    app.kubernetes.io/instance: nats
    app.kubernetes.io/component: nats
  name: nats-headless
  namespace: {{ $namespace }}
spec:
  clusterIP: None
  ports:
    - appProtocol: tcp
      name: nats
      port: 4222
      targetPort: nats
    - appProtocol: http
      name: monitor
      port: 8222
      targetPort: monitor
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: nats
    app.kubernetes.io/instance: nats
    app.kubernetes.io/component: nats
---
# Source: nats/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: nats
    app.kubernetes.io/instance: nats
    app.kubernetes.io/component: nats
  name: nats
  namespace: {{ $namespace }}
spec:
  ports:
    - appProtocol: tcp
      name: nats
      port: 4222
      targetPort: nats
  selector:
    app.kubernetes.io/name: nats
    app.kubernetes.io/instance: nats
    app.kubernetes.io/component: nats
---
# Source: nats/templates/stateful-set.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/component: nats
    app.kubernetes.io/name: nats
    app.kubernetes.io/instance: nats
    applications.app.bytetrade.io/author: bytetrade.io
  name: nats
  namespace: {{ $namespace }}
spec:
  podManagementPolicy: Parallel
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: nats
      app.kubernetes.io/name: nats
      app.kubernetes.io/instance: nats
  serviceName: {{ .Release.Name}}-headless
  template:
    metadata:
      annotations:
        checksum/config: e37e733aab5e99b5d785f54115b3c34dfb02b80d350b62e5b211794a2ad060ec
      labels:
        app.kubernetes.io/component: nats
        app.kubernetes.io/name: nats
        app.kubernetes.io/instance: nats
        app.bytetrade.io/middleware: "true"
    spec:
      priorityClassName: "system-cluster-critical"
      serviceAccountName: nats
      serviceAccount: nats
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: Exists
      initContainers:
      - name: cm-sidecar
        image: beclab/cm-sidecar:0.0.1
        imagePullPolicy: IfNotPresent
        restartPolicy: Always
        env:
        - name: CONFIGMAP_TARGET_DIR
          value: /data/config
        startupProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 1
          failureThreshold: 60
        volumeMounts:
        - mountPath: /data/config
          name: nats-cfg
      containers:
        - name: nats
          args:
          - --config
          - /data/config/nats.conf
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SERVER_NAME
              value: $(POD_NAME)
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nats-secrets
                  key: nats_password
          image: nats:2.10.17-alpine
          lifecycle:
            preStop:
              exec:
                command:
                  - nats-server
                  - -sl=ldm=/var/run/nats/nats.pid
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz?js-enabled-only=true
              port: monitor
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 5
          ports:
            - containerPort: 4222
              name: nats
            - containerPort: 8222
              name: monitor
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz?js-server-only=true
              port: monitor
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          startupProbe:
            failureThreshold: 90
            httpGet:
              path: /healthz
              port: monitor
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          volumeMounts:
            - mountPath: /var/run/nats
              name: pid
            - mountPath: /data
              name: nats-data
            - mountPath: /data/config
              name: nats-cfg
        - args:
            - -pid
            - /var/run/nats/nats.pid
            - -config
            - /data/config/nats.conf
          image: beclab/nats-server-config-reloader:v1
          name: reloader
          env:
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nats-secrets
                  key: nats_password
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              add:
                - SYS_PTRACE
          volumeMounts:
            - mountPath: /var/run/nats
              name: pid
            - mountPath: /data
              name: nats-data
            - mountPath: /data/config
              name: nats-cfg
      enableServiceLinks: false
      shareProcessNamespace: true
      volumes:
        - emptyDir: {}
          name: nats-cfg
        - emptyDir: {}
          name: pid
        - name: nats-data
          persistentVolumeClaim:
            claimName: nats-data-pvc
