
---
apiVersion: v1
kind: Service
metadata:
  name: recommend
  namespace: {{ .Release.Namespace }}
spec:
  type: ExternalName
  externalName: argoworkflows-svc.{{ .Release.Namespace }}.svc.cluster.local
  ports:
    - name: http
      port: 2746
      protocol: TCP
      targetPort: 2746

---
apiVersion: v1
kind: Service
metadata:
  name: argoworkflows-ui
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: recommend
  type: ClusterIP



---
apiVersion: v1
data:
  nginx.conf: |
    # Configuration checksum:

    pid /var/run/nginx.pid;

    worker_processes auto;

    events {
      worker_connections 1024;
    }

    http {
      server {
        listen 8080;

        location / {
          proxy_pass http://recommend:2746;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
      }
    }
kind: ConfigMap
metadata:
  name: recommend-nginx-configs
  namespace: {{ .Release.Namespace }}

