
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-cluster-mongos
  namespace: user-system-{{ .Values.bfl.username }}
spec:
  type: ClusterIP
  selector:
    app: systemserver
  ports:
    - protocol: TCP
      name: mongos
      port: 27017
      targetPort: 27017

# mongo request demo
# ---
# apiVersion: apr.bytetrade.io/v1alpha1
# kind: MiddlewareRequest
# metadata:
#   name: test-mdb
#   namespace: user-system-{{ .Values.bfl.username }}
# spec:
#   app: test
#   appNamespace: user-space-{{ .Values.bfl.username }}
#   middleware: mongodb
#   mongodb:
#     user: testuser
#     password: 
#       value: mongo
#     databases:
#     - testdb 
