package templates

import (
	"text/template"

	"github.com/lithammer/dedent"
)

// The drop-ins below keep the processes kubelet needs, in order to relieve memory
// pressure, resident while it is relieving it.
//
// They have to be written as a set, and the reason is easy to get wrong: cgroup
// v2 clamps a cgroup's effective memory.min by that of every ancestor, and
// system.slice's default is zero. A configuration that sets the per-service
// values and not the slice therefore reads as if it protects them while
// reclaiming just as much as no configuration at all.
//
// MemorySwapMax=0 is needed alongside memory.min because the two do different
// things: memory.min makes a cgroup an unattractive reclaim target, while
// MemorySwapMax=0 leaves the kernel nowhere to put its pages.
//
// A node that swaps its control plane out does not merely slow down. k3s stops
// renewing its leader election lease and restarts into the same pressure, and
// each containerd-shim needed to stop a container has to be faulted back in one
// major fault at a time — so the node has decided to evict but cannot act on it.
var (
	// HostMemoryProtectionSlice raises the ceiling that the per-service files
	// live under. Everything host-side shares system.slice, so this is the one
	// value that has to cover them all.
	// The template names differ only because action.Template stages the rendered
	// file locally under Name() before copying it to Dst; on the node they all
	// land as 10-olares-memory.conf in their own drop-in directory.
	HostMemoryProtectionSlice = template.Must(template.New("system.slice-memory.conf").Parse(
		dedent.Dedent(`# Generated by olares-cli. See pkg/utils/kubelet_reserved.go.
		#
		# Without this, the MemoryMin in k3s.service.d and containerd.service.d
		# is silently reduced to zero: cgroup v2 limits a cgroup's effective
		# protection to what its ancestors protect, and system.slice defaults to
		# protecting nothing.
		#
		# This stays at or below the memory kubelet holds back from pods, so the
		# kernel is never promised memory the scheduler has already given away.
		[Slice]
		MemoryMin={{ .SystemSliceMemoryMin }}
		`)))

	// HostMemoryProtectionK3s covers the control plane and kubelet: the eviction
	// manager, and on a master the API server it has to reach to act on what it
	// decides.
	HostMemoryProtectionK3s = template.Must(template.New("k3s.service-memory.conf").Parse(
		dedent.Dedent(`# Generated by olares-cli. See pkg/utils/kubelet_reserved.go.
		#
		# MemorySwapMax keeps the heap in RAM. MemoryMin additionally covers the
		# file-backed pages, which for a binary this size means k3s does not have
		# to fault its own text back in to run the code that relieves the
		# pressure.
		#
		# Requires the matching drop-in under system.slice.d to take effect.
		[Service]
		MemoryMin={{ .K3sMemoryMin }}
		MemorySwapMax=0
		`)))

	// HostMemoryProtectionContainerd covers containerd and, because they share
	// its cgroup, every containerd-shim on the node. A shim is what actually
	// stops a container, so swapping them out is what turns a node that has
	// decided to evict into one that cannot carry it out.
	HostMemoryProtectionContainerd = template.Must(template.New("containerd.service-memory.conf").Parse(
		dedent.Dedent(`# Generated by olares-cli. See pkg/utils/kubelet_reserved.go.
		#
		# Covers the shims as well as containerd itself; they live in this cgroup.
		# The containers do not — they are under kubepods.slice — so this does not
		# change what a pod may use.
		#
		# Requires the matching drop-in under system.slice.d to take effect.
		[Service]
		MemoryMin={{ .ContainerdMemoryMin }}
		MemorySwapMax=0
		`)))

	// HostMemoryProtectionEtcd covers the datastore. Olares runs etcd as its own
	// unit rather than using the copy embedded in k3s, so k3s.service's drop-in
	// does nothing for it and it needs its own.
	//
	// This one is the least optional of the set. Everything else degrades when it
	// is paged out; etcd stops the cluster.
	HostMemoryProtectionEtcd = template.Must(template.New("etcd.service-memory.conf").Parse(
		dedent.Dedent(`# Generated by olares-cli. See pkg/utils/kubelet_reserved.go.
		#
		# etcd fsyncs its write-ahead log on the path of every write and defends a
		# 100ms heartbeat against a 1s election timeout. Reading a page back from
		# swap inside that budget loses the leader, and every write in the cluster
		# blocks until the election ends.
		#
		# MemoryMin is set above the anonymous memory etcd holds on purpose: the
		# database and the log are read through mmap, so they are file-backed, and
		# protecting only the heap would leave the part that gets fsynced exposed.
		#
		# Requires the matching drop-in under system.slice.d to take effect.
		[Service]
		MemoryMin={{ .EtcdMemoryMin }}
		MemorySwapMax=0
		`)))
)
