{{- $namespace := printf "%s%s" "user-system-" .Values.bfl.username -}}
{{- $download_secret := (lookup "v1" "Secret" $namespace "rss-secrets") -}}

{{- $pg_password := "" -}}
{{ if $download_secret -}}
{{ $pg_password = (index $download_secret "data" "pg_password") }}
{{ else -}}
{{ $pg_password = randAlphaNum 16 | b64enc }}
{{- end -}}

---
apiVersion: v1
kind: Secret
metadata:
  name: download-secrets
  namespace: user-system-{{ .Values.bfl.username }}
type: Opaque
data:
  pg_password: {{ $pg_password }}
---
apiVersion: apr.bytetrade.io/v1alpha1
kind: MiddlewareRequest
metadata:
  name: download-pg
  namespace: user-system-{{ .Values.bfl.username }}
spec:
  app: download
  appNamespace: {{ .Release.Namespace }}
  middleware: postgres
  postgreSQL:
    user: knowledge_{{ .Values.bfl.username }}
    password:
      valueFrom:
        secretKeyRef:
          key: pg_password
          name: download-secrets
    databases:
    - name: knowledge


---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: download
  namespace: {{ .Release.Namespace }}
  labels:
    app: download
    applications.app.bytetrade.io/author: bytetrade.io
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: download
  template:
    metadata:
      labels:
        app: download
    spec:
      containers:
      - name: aria2
        image: "cesign/aria2-pro"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6800
        - containerPort: 6888
        env:
        - name: RPC_SECRET
          value: kubespider
        - name: PUID
          value: "0"
        - name: PGID
          value: "0"
        volumeMounts:
        - name: config-dir
          mountPath: /config
        - name: download-dir
          mountPath: /downloads
        resources:
          requests:
            cpu: 20m
            memory: 50Mi
          limits:
            cpu: "1"
            memory: 300Mi
      - name: yt-dlp
        image: "beclab/yt-dlp:v0.0.1"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3082
        env:
        - name: PG_USERNAME
          value: knowledge_{{ .Values.bfl.username }}
        - name: PG_PASSWORD
          value: {{ $pg_password | b64dec }}
        - name: PG_HOST
          value: citus-master-svc.user-system-{{ .Values.bfl.username }}
        - name: PG_PORT
          value: "5432"
        - name: PG_DATABASE
          value: user_space_{{ .Values.bfl.username }}_knowledge
        volumeMounts:
        - name: config-dir
          mountPath: /app/config
        - name: download-dir
          mountPath: /app/downloads
        resources:
          requests:
            cpu: 20m
            memory: 50Mi
          limits:
            cpu: "1"
            memory: 300Mi

      - name: download-spider
        image: "beclab/download-spider:v0.0.1"
        imagePullPolicy: IfNotPresent
        env:
        - name: PG_USERNAME
          value: knowledge_{{ .Values.bfl.username }}
        - name: PG_PASSWORD
          value: {{ $pg_password | b64dec }}
        - name: PG_HOST
          value: citus-master-svc.user-system-{{ .Values.bfl.username }}
        - name: PG_PORT
          value: "5432"
        - name: PG_DATABASE
          value: user_space_{{ .Values.bfl.username }}_knowledge
        
        ports:
        - containerPort: 3080
        resources:
          requests:
            cpu: 20m
            memory: 50Mi
          limits:
            cpu: "1"
            memory: 300Mi

      volumes:
      - name: config-dir
        hostPath:
          type: DirectoryOrCreate
          path: {{ .Values.userspace.userData }}/Download/config
      - name: download-dir
        hostPath:
          type: DirectoryOrCreate
          path: {{ .Values.userspace.userData }}/Download


---
apiVersion: v1
kind: Service
metadata:
  name: download-svc
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: download
  ports:
    - name: "download-spider"
      protocol: TCP
      port: 3080
      targetPort: 3080
    - name: "aria2-server"
      protocol: TCP
      port: 6800
      targetPort: 6800

---
apiVersion: v1
kind: Service
metadata:
  name: download-api
  namespace: user-system-{{ .Values.bfl.username }}
spec:
  type: ClusterIP
  selector:
    app: systemserver
  ports:
    - protocol: TCP
      name: download-api
      port: 3080
      targetPort: 3080  


