{{- if .Values.extAuthz.enabled }}
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: {{ .Values.extAuthz.name }}
  namespace: {{ include "app-gateway.namespace" . }}
  labels:
    app.kubernetes.io/name: app-gateway
    app.kubernetes.io/component: ext-authz
    applications.app.bytetrade.io/author: bytetrade.io
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ .Values.gateway.name }}
  extAuth:
    failOpen: {{ .Values.extAuthz.failOpen }}
    grpc:
      backendRefs:
        - name: {{ .Values.extAuthz.service.name }}
          namespace: {{ include "app-gateway.namespace" . }}
          port: {{ .Values.extAuthz.service.port }}
{{- end }}
