export const ROUTE_CONST = {
	COLLECT: 'COLLECT',
	TRANSLATE: 'TRANSLATE',
	OPTIONS_APPEARANCE: 'OPTIONS_APPEARANCE',
	OPTIONS_COLLECT: 'OPTIONS_COLLECT',
	OPTIONS_TRANSLATE: 'OPTIONS_TRANSLATE',
	OPTIONS_SECURITY: 'OPTIONS_SECURITY',
	OPTIONS_ACCOUNT: 'OPTIONS_ACCOUNT',
	OPTIONS_ACCOUNT_IMPORT: 'OPTIONS_ACCOUNT_IMPORT',
	OPTIONS_ACCOUNT_LIST: 'OPTIONS_ACCOUNT_LIST',
	OPTIONS_ACCOUNT_CONNECT_TERMINUS_BEX: 'OPTIONS_ACCOUNT_CONNECT_TERMINUS_BEX'
} as const;

export type RouteNames = (typeof ROUTE_CONST)[keyof typeof ROUTE_CONST];
