target: prebuilt
output:
  binaries:
    - 
      id: kubeadm
      name: kubeadm-v1.32.2,pkg/kube/v1.32.2
      amd64: https://dl.k8s.io/release/v1.32.2/bin/linux/amd64/kubeadm
      arm64: https://dl.k8s.io/release/v1.32.2/bin/linux/arm64/kubeadm
    - 
      id: kubelet
      name: kubelet-v1.32.2,pkg/kube/v1.32.2
      amd64: https://dl.k8s.io/release/v1.32.2/bin/linux/amd64/kubelet
      arm64: https://dl.k8s.io/release/v1.32.2/bin/linux/arm64/kubelet
    - 
      id: kubectl
      name: kubectl-v1.32.2,pkg/kube/v1.32.2
      amd64: https://dl.k8s.io/release/v1.32.2/bin/linux/amd64/kubectl
      arm64: https://dl.k8s.io/release/v1.32.2/bin/linux/arm64/kubectl
  containers:
    - 
      name: beclab/ks-apiserver:0.0.11
    - 
      name: beclab/ks-controller-manager:0.0.11
    -
      name: kubesphere/kubectl:v1.22.0
    -
      name: owncloudci/wait-for:latest
    -
      name: liangjw/kube-webhook-certgen:v1.1.1
    - 
      name: alpine:3.14
    -
      name: mirrorgooglecontainers/defaultbackend-amd64:1.4