apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: os-system:argoworkflows
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argoworkflows
subjects:
  - kind: ServiceAccount
    name: argoworkflows
    namespace: os-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: os-system:argoworkflows-cluster-template
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argoworkflows-cluster-template
subjects:
  - kind: ServiceAccount
    name: argoworkflows
    namespace: os-system
