

---
apiVersion: v1
kind: Secret
metadata:
  name: argo-workflow-log-fakes3
  namespace: os-system
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: S3RVER
  AWS_SECRET_ACCESS_KEY: S3RVER

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workflow-role
  namespace: os-system
rules:
- apiGroups:
  - "*"
  resources:
  - pods
  verbs:
  - patch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workflow-rolebinding
  namespace: os-system
subjects:
  - kind: ServiceAccount
    namespace: os-system
    name: default
roleRef:
  kind: Role
  name: workflow-role
  apiGroup: rbac.authorization.k8s.io