package cookieparse

import (
	"encoding/json"
	"strings"
	"testing"
	"time"
)

func netscapeLine(domain, name, value, expires string) string {
	return strings.Join([]string{domain, "TRUE", "/", "TRUE", expires, name, value}, "\t")
}

func recordByName(t *testing.T, res *Result, domain, name string) Record {
	t.Helper()
	for _, r := range res.Cookies[domain] {
		if r.Name == name {
			return r
		}
	}
	t.Fatalf("no cookie %q under domain %q (have %+v)", name, domain, res.Cookies)
	return Record{}
}

func TestNetscapeKeepsHTTPOnlyRecords(t *testing.T) {
	text := strings.Join([]string{
		"# Netscape HTTP Cookie File",
		"# This file is generated by yt-dlp.  Do not edit.",
		"",
		netscapeLine(".youtube.com", "PREF", "tz=Asia.Shanghai", "1780000000"),
		netscapeLine("#HttpOnly_.youtube.com", "SID", "sid-value", "1780000000"),
		netscapeLine("#HttpOnly_.youtube.com", "__Secure-3PSID", "psid-value", "1780000000"),
		netscapeLine("#HttpOnly_.youtube.com", "HSID", "hsid-value", "1780000000"),
	}, "\n")

	res, format, err := Parse(text, FormatAuto, "")
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	if format != FormatNetscape {
		t.Fatalf("detected format = %q, want netscape", format)
	}
	if len(res.InvalidLines) != 0 {
		t.Fatalf("unexpected invalid lines: %v", res.InvalidLines)
	}
	if got := res.Count(); got != 4 {
		t.Fatalf("parsed %d records, want 4 (httpOnly records must survive)", got)
	}

	for _, name := range []string{"SID", "__Secure-3PSID", "HSID"} {
		if rec := recordByName(t, res, ".youtube.com", name); !rec.HttpOnly {
			t.Errorf("cookie %q: HttpOnly = false, want true", name)
		}
	}
	if rec := recordByName(t, res, ".youtube.com", "PREF"); rec.HttpOnly {
		t.Error("cookie PREF: HttpOnly = true, want false")
	}
}

func TestNetscapeStripsPrefixFromStoredDomain(t *testing.T) {
	res, _, err := Parse(netscapeLine("#HttpOnly_.youtube.com", "SID", "v", "0"), FormatNetscape, "")
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	if _, ok := res.Cookies[".youtube.com"]; !ok {
		t.Fatalf("domains = %v, want [.youtube.com]", res.Domains())
	}
}

func TestNetscapeIgnoresRealComments(t *testing.T) {
	text := strings.Join([]string{
		"# Netscape HTTP Cookie File",
		"#",
		"# https://curl.se/docs/http-cookies.html",
		netscapeLine(".example.com", "a", "b", "1780000000"),
	}, "\n")

	res, _, err := Parse(text, FormatNetscape, "")
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	if len(res.InvalidLines) != 0 {
		t.Fatalf("unexpected invalid lines: %v", res.InvalidLines)
	}
	if got := res.Count(); got != 1 {
		t.Fatalf("parsed %d records, want 1", got)
	}
}

func TestNetscapeDetectsAnAllHTTPOnlyFile(t *testing.T) {
	text := strings.Join([]string{
		"# Netscape HTTP Cookie File",
		netscapeLine("#HttpOnly_.youtube.com", "SID", "sid", "1780000000"),
		netscapeLine("#HttpOnly_.youtube.com", "HSID", "hsid", "1780000000"),
	}, "\n")

	p := Detect(text)
	if p == nil || p.Format() != FormatNetscape {
		t.Fatalf("Detect = %v, want netscape", p)
	}
}

func TestNetscapeToleratesCRLF(t *testing.T) {
	text := strings.Join([]string{
		"# Netscape HTTP Cookie File",
		netscapeLine("#HttpOnly_.youtube.com", "SID", "sid-value", "1780000000"),
	}, "\r\n")

	res, _, err := Parse(text, FormatNetscape, "")
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	if len(res.InvalidLines) != 0 {
		t.Fatalf("unexpected invalid lines: %v", res.InvalidLines)
	}
	if rec := recordByName(t, res, ".youtube.com", "SID"); rec.Value != "sid-value" {
		t.Fatalf("value = %q, want sid-value", rec.Value)
	}
}

func TestNetscapeKeepsSessionCookies(t *testing.T) {
	res, _, err := Parse(netscapeLine(".example.com", "sess", "v", "0"), FormatNetscape, "")
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	if len(res.InvalidLines) != 0 {
		t.Fatalf("expires=0 must be kept as a session cookie, got: %v", res.InvalidLines)
	}
	if rec := recordByName(t, res, ".example.com", "sess"); rec.ExpiryUnix() != 0 {
		t.Fatalf("expires = %d, want 0", rec.ExpiryUnix())
	}
}

func TestNetscapeRejectsJSONWithAClearMessage(t *testing.T) {
	_, _, err := Parse(`[{"domain":".example.com","name":"a","value":"b"}]`, FormatNetscape, "")
	if err == nil || !strings.Contains(strings.ToLower(err.Error()), "json") {
		t.Fatalf("err = %v, want a message naming JSON", err)
	}
}

func TestNetscapeKeepsTabsInsideValues(t *testing.T) {
	line := strings.Join([]string{".example.com", "TRUE", "/", "FALSE", "0", "n", "a\tb"}, "\t")

	res, _, err := Parse(line, FormatNetscape, "")
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	if rec := recordByName(t, res, ".example.com", "n"); rec.Value != "a\tb" {
		t.Fatalf("value = %q, want %q", rec.Value, "a\tb")
	}
}

func TestExpiryIsWrittenToBothFieldNames(t *testing.T) {
	res, _, err := Parse(netscapeLine(".example.com", "a", "b", "1780000000"), FormatNetscape, "")
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	rec := recordByName(t, res, ".example.com", "a")
	if rec.Expires != 1780000000 {
		t.Errorf("Expires = %v, want 1780000000", rec.Expires)
	}
	// download-server and the yt-dlp daemon read expirationDate, not expires.
	if rec.ExpirationDate != rec.Expires {
		t.Errorf("ExpirationDate = %v, want %v", rec.ExpirationDate, rec.Expires)
	}
}

// The SPA stores Date.now()/1000, so records already in Infisical carry
// fractional seconds. Decoding them must not fail.
func TestRecordDecodesAFractionalExpiry(t *testing.T) {
	var rec Record
	raw := `{"domain":".youtube.com","name":"SID","value":"v","expires":1800711300.517479}`
	if err := json.Unmarshal([]byte(raw), &rec); err != nil {
		t.Fatalf("unmarshal: %v", err)
	}
	if got := rec.ExpiryUnix(); got != 1800711300 {
		t.Errorf("ExpiryUnix = %d, want 1800711300", got)
	}
}

func TestJSONParsesExtensionExports(t *testing.T) {
	text := `[
		{"domain":".youtube.com","name":"SID","value":"sid","path":"/","secure":true,"httpOnly":true,"expirationDate":1780000000.75},
		{"domain":".youtube.com","name":"PREF","value":"tz","expires":1770000000}
	]`

	res, format, err := Parse(text, FormatAuto, "")
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	if format != FormatJSON {
		t.Fatalf("detected format = %q, want json", format)
	}

	sid := recordByName(t, res, ".youtube.com", "SID")
	if !sid.HttpOnly || !sid.Secure {
		t.Errorf("SID flags: httpOnly=%v secure=%v, want both true", sid.HttpOnly, sid.Secure)
	}
	if sid.ExpiryUnix() != 1780000000 {
		t.Errorf("SID expires = %d, want 1780000000 (truncated from expirationDate)", sid.ExpiryUnix())
	}
	if pref := recordByName(t, res, ".youtube.com", "PREF"); pref.ExpiryUnix() != 1770000000 {
		t.Errorf("PREF expires = %d, want 1770000000", pref.ExpiryUnix())
	}
}

func TestJSONAcceptsAWrappedObject(t *testing.T) {
	res, _, err := Parse(`{"cookies":[{"domain":".example.com","name":"a","value":"b"}]}`, FormatJSON, "")
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	if got := res.Count(); got != 1 {
		t.Fatalf("parsed %d records, want 1", got)
	}
}

func TestJSONAcceptsASingleObject(t *testing.T) {
	res, _, err := Parse(`{"domain":".example.com","name":"a","value":"b"}`, FormatJSON, "")
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	if got := res.Count(); got != 1 {
		t.Fatalf("parsed %d records, want 1", got)
	}
}

func TestHeaderSplitsABrowserCookieLine(t *testing.T) {
	res, _, err := Parse("SID=sid-value; HSID=hsid-value; PREF=tz=Asia.Shanghai", FormatHeader, ".youtube.com")
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	if got := res.Count(); got != 3 {
		t.Fatalf("parsed %d records, want 3", got)
	}
	// A value may itself contain '='; only the first one separates.
	if rec := recordByName(t, res, ".youtube.com", "PREF"); rec.Value != "tz=Asia.Shanghai" {
		t.Fatalf("PREF value = %q, want tz=Asia.Shanghai", rec.Value)
	}
}

func TestHeaderDetectsASingleLineBrowserCookie(t *testing.T) {
	// YouTube / DevTools style: one long request Cookie line, no tabs,
	// no Set-Cookie attributes — must clear Detect's threshold of 5.
	text := "SID=sid-value; HSID=hsid-value; PREF=tz=Asia.Shanghai; __Secure-3PSID=psid"

	p := Detect(text)
	if p == nil || p.Format() != FormatHeader {
		t.Fatalf("Detect = %v, want header", p)
	}
	if score := (headerParser{}).Detect(text); score < 5 {
		t.Fatalf("header Detect score = %d, want >= 5", score)
	}
	if (netscapeParser{}).Detect(text) >= 5 {
		t.Fatalf("netscape must not claim a Cookie header")
	}
	if (jsonParser{}).Detect(text) != 0 {
		t.Fatalf("json must not claim a Cookie header")
	}

	res, format, err := Parse(text, FormatAuto, ".youtube.com")
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	if format != FormatHeader {
		t.Fatalf("detected format = %q, want header", format)
	}
	if got := res.Count(); got != 4 {
		t.Fatalf("parsed %d records, want 4", got)
	}
}

func TestDetectKeepsNetscapeOverHeader(t *testing.T) {
	text := "# Netscape HTTP Cookie File\n" +
		".youtube.com\tTRUE\t/\tFALSE\t0\tSID\tsid-value\n" +
		".youtube.com\tTRUE\t/\tTRUE\t0\tHSID\thsid-value\n"

	p := Detect(text)
	if p == nil || p.Format() != FormatNetscape {
		t.Fatalf("Detect = %v, want netscape", p)
	}
}

func TestHeaderDetectsCookiePrefixedBrowserLine(t *testing.T) {
	text := "Cookie: SID=sid-value; HSID=hsid-value"

	p := Detect(text)
	if p == nil || p.Format() != FormatHeader {
		t.Fatalf("Detect = %v, want header", p)
	}

	res, format, err := Parse(text, FormatAuto, "youtube.com")
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	if format != FormatHeader {
		t.Fatalf("detected format = %q, want header", format)
	}
	if got := res.Count(); got != 2 {
		t.Fatalf("parsed %d records, want 2", got)
	}
}

func TestHeaderRequiresADomainForBrowserLines(t *testing.T) {
	res, _, err := Parse("SID=sid-value; HSID=hsid-value", FormatHeader, "")
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	if res.Count() != 0 {
		t.Fatalf("parsed %d records, want 0 without a domain", res.Count())
	}
	if !res.NeedsDomain {
		t.Fatal("NeedsDomain = false, want true for a domain-less request Cookie header")
	}
	if len(res.InvalidLines) != 1 {
		t.Fatalf("invalid lines = %v, want one reject for the whole line", res.InvalidLines)
	}
	msg := res.InvalidLines[0]
	if !strings.Contains(msg, "pass --domain") {
		t.Fatalf("invalid = %q, want pass --domain", msg)
	}
	for _, name := range []string{"SID", "HSID", "sid-value", "hsid-value"} {
		if strings.Contains(msg, name) {
			t.Fatalf("InvalidLines must not embed cookie name/value %q: %q", name, msg)
		}
	}
}

func TestNeedsDomainOnlyForBareRequestCookieHeader(t *testing.T) {
	cases := []struct {
		name   string
		text   string
		format Format
		domain string
		want   bool
	}{
		{
			name:   "bare request header",
			text:   "SID=a; HSID=b",
			format: FormatHeader,
			want:   true,
		},
		{
			name:   "request header with domain",
			text:   "SID=a; HSID=b",
			format: FormatHeader,
			domain: ".youtube.com",
			want:   false,
		},
		{
			name:   "set-cookie missing domain",
			text:   "Set-Cookie: SID=x; Path=/; Secure",
			format: FormatHeader,
			want:   false,
		},
		{
			name:   "set-cookie invalid expires",
			text:   "Set-Cookie: SID=x; Expires=not-a-date; Domain=.youtube.com",
			format: FormatHeader,
			want:   false,
		},
		{
			name:   "empty cookie name",
			text:   "Set-Cookie: =y; Path=/; Domain=.youtube.com",
			format: FormatHeader,
			want:   false,
		},
		{
			name:   "not a cookie assignment",
			text:   "not-a-cookie-line",
			format: FormatHeader,
			want:   false,
		},
		{
			name:   "netscape",
			text:   "# Netscape HTTP Cookie File\n.youtube.com\tTRUE\t/\tFALSE\t0\tSID\tv\n",
			format: FormatNetscape,
			want:   false,
		},
		{
			name:   "json",
			text:   `[{"domain":".youtube.com","name":"SID","value":"v"}]`,
			format: FormatJSON,
			want:   false,
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			res, _, err := Parse(tc.text, tc.format, tc.domain)
			if err != nil {
				t.Fatalf("parse: %v", err)
			}
			if res.NeedsDomain != tc.want {
				t.Fatalf("NeedsDomain = %v, want %v", res.NeedsDomain, tc.want)
			}
		})
	}
}

func TestHeaderSetCookieMissingDomainOmitsName(t *testing.T) {
	res, _, err := Parse("Set-Cookie: SID=sid-value; Path=/", FormatHeader, "")
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	if res.Count() != 0 {
		t.Fatalf("parsed %d, want 0", res.Count())
	}
	if len(res.InvalidLines) != 1 {
		t.Fatalf("invalid = %v", res.InvalidLines)
	}
	msg := res.InvalidLines[0]
	if !strings.Contains(msg, "pass --domain") {
		t.Fatalf("invalid = %q, want pass --domain", msg)
	}
	for _, leak := range []string{"SID", "sid-value"} {
		if strings.Contains(msg, leak) {
			t.Fatalf("InvalidLines must not embed %q: %q", leak, msg)
		}
	}
}

func TestJSONMissingDomainOmitsName(t *testing.T) {
	res, _, err := Parse(`[{"name":"SID","value":"secret"}]`, FormatJSON, "")
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	if len(res.InvalidLines) != 1 {
		t.Fatalf("invalid = %v", res.InvalidLines)
	}
	msg := res.InvalidLines[0]
	for _, leak := range []string{"SID", "secret"} {
		if strings.Contains(msg, leak) {
			t.Fatalf("InvalidLines must not embed %q: %q", leak, msg)
		}
	}
}

func TestHeaderReadsSetCookieAttributes(t *testing.T) {
	text := "Set-Cookie: SID=sid-value; Domain=.youtube.com; Path=/x; Secure; HttpOnly; SameSite=None; Expires=Wed, 21 Oct 2026 07:28:00 GMT"

	res, _, err := Parse(text, FormatHeader, "")
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	rec := recordByName(t, res, ".youtube.com", "SID")
	if !rec.Secure || !rec.HttpOnly {
		t.Errorf("flags: secure=%v httpOnly=%v, want both true", rec.Secure, rec.HttpOnly)
	}
	if rec.SameSite != "None" {
		t.Errorf("sameSite = %q, want None", rec.SameSite)
	}
	if rec.Path != "/x" {
		t.Errorf("path = %q, want /x", rec.Path)
	}
	want := time.Date(2026, 10, 21, 7, 28, 0, 0, time.UTC).Unix()
	if rec.ExpiryUnix() != want {
		t.Errorf("expires = %d, want %d", rec.ExpiryUnix(), want)
	}
}

func TestHeaderStripsARequestCookiePrefix(t *testing.T) {
	res, _, err := Parse("Cookie: SID=sid-value; HSID=hsid", FormatHeader, ".youtube.com")
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	if got := res.Count(); got != 2 {
		t.Fatalf("parsed %d records, want 2", got)
	}
}

func TestHeaderMaxAgeBecomesAnAbsoluteExpiry(t *testing.T) {
	before := time.Now().Unix()
	res, _, err := Parse("Set-Cookie: a=b; Domain=.example.com; Max-Age=3600", FormatHeader, "")
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	rec := recordByName(t, res, ".example.com", "a")
	if rec.ExpiryUnix() < before+3600 || rec.ExpiryUnix() > time.Now().Unix()+3600 {
		t.Fatalf("expires = %d, want roughly now+3600", rec.ExpiryUnix())
	}
}

func TestDomainFlagOverridesTheParsedDomain(t *testing.T) {
	res, _, err := Parse(netscapeLine(".youtube.com", "SID", "v", "0"), FormatNetscape, ".override.com")
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	if _, ok := res.Cookies[".override.com"]; !ok {
		t.Fatalf("domains = %v, want [.override.com]", res.Domains())
	}
}

func TestParseRejectsEmptyInput(t *testing.T) {
	if _, _, err := Parse("   \n  ", FormatAuto, ""); err == nil {
		t.Fatal("want an error for empty input")
	}
}

func TestParseFormatValidation(t *testing.T) {
	for _, in := range []string{"", "auto", "AUTO", "netscape", "json", "header"} {
		if _, err := ParseFormat(in); err != nil {
			t.Errorf("ParseFormat(%q) = %v, want ok", in, err)
		}
	}
	if _, err := ParseFormat("yaml"); err == nil {
		t.Error("ParseFormat(yaml) should fail")
	}
}

// InvalidLines are printed by `cookie import`; they must never carry
// cookie values (shell history / CI logs / agent chat).
func TestInvalidLinesNeverEchoSecrets(t *testing.T) {
	const secret = "super-secret-cookie-value"

	t.Run("netscape short line", func(t *testing.T) {
		// Six fields only — the dangling seventh fragment is a secret.
		res, _, err := Parse(".youtube.com\tTRUE\t/\tFALSE\t0\t"+secret, FormatNetscape, "")
		if err != nil {
			t.Fatalf("parse: %v", err)
		}
		if res.Count() != 0 {
			t.Fatalf("want reject, got %d records", res.Count())
		}
		assertInvalidLinesSafe(t, res.InvalidLines, secret)
	})

	t.Run("netscape empty domain", func(t *testing.T) {
		res, _, err := Parse("\tTRUE\t/\tFALSE\t0\tSID\t"+secret, FormatNetscape, "")
		if err != nil {
			t.Fatalf("parse: %v", err)
		}
		assertInvalidLinesSafe(t, res.InvalidLines, secret)
	})

	t.Run("netscape bad path", func(t *testing.T) {
		res, _, err := Parse(".youtube.com\tTRUE\trelative\tFALSE\t0\tSID\t"+secret, FormatNetscape, "")
		if err != nil {
			t.Fatalf("parse: %v", err)
		}
		assertInvalidLinesSafe(t, res.InvalidLines, secret)
	})

	t.Run("netscape secret in path column", func(t *testing.T) {
		res, _, err := Parse(".youtube.com\tTRUE\t"+secret+"\tFALSE\t0\tSID\tok", FormatNetscape, "")
		if err != nil {
			t.Fatalf("parse: %v", err)
		}
		assertInvalidLinesSafe(t, res.InvalidLines, secret)
	})

	t.Run("netscape secret in expiration column", func(t *testing.T) {
		res, _, err := Parse(".youtube.com\tTRUE\t/\tFALSE\t"+secret+"\tSID\tok", FormatNetscape, "")
		if err != nil {
			t.Fatalf("parse: %v", err)
		}
		assertInvalidLinesSafe(t, res.InvalidLines, secret)
	})

	t.Run("json nameless object", func(t *testing.T) {
		res, _, err := Parse(`[{"value":"`+secret+`","domain":".youtube.com"}]`, FormatJSON, "")
		if err != nil {
			t.Fatalf("parse: %v", err)
		}
		if len(res.InvalidLines) != 1 {
			t.Fatalf("invalid = %v", res.InvalidLines)
		}
		assertInvalidLinesSafe(t, res.InvalidLines, secret)
	})

	t.Run("header empty name", func(t *testing.T) {
		res, _, err := Parse("Set-Cookie: ="+secret+"; Domain=.youtube.com", FormatHeader, "")
		if err != nil {
			t.Fatalf("parse: %v", err)
		}
		assertInvalidLinesSafe(t, res.InvalidLines, secret)
	})

	t.Run("header secret in expires attribute", func(t *testing.T) {
		res, _, err := Parse("Set-Cookie: SID=ok; Domain=.youtube.com; Expires="+secret, FormatHeader, "")
		if err != nil {
			t.Fatalf("parse: %v", err)
		}
		assertInvalidLinesSafe(t, res.InvalidLines, secret)
	})
}

func assertInvalidLinesSafe(t *testing.T, lines []string, secret string) {
	t.Helper()
	if len(lines) == 0 {
		t.Fatal("want at least one invalid line")
	}
	for _, line := range lines {
		if strings.Contains(line, secret) {
			t.Fatalf("InvalidLines leak secret: %q", line)
		}
	}
}
