package controllers

// Lineage-driven payload dump (golden file) for the controller's state
// machine. Each lineage starts at <none>, drives the AM through a
// sequence of production-equivalent steps (handler writes or Reconcile
// ticks), and records the (state, op, message, reason) tuple after every
// step. The full set of lineages is rendered to a self-contained HTML
// document (state_flow_pushed_messages.html) and compared byte-for-byte
// against the committed golden file in source.
//
// state_flow_pushed_messages.html is fully generated by this test —
// CSS, JS, layout and data are all driven from Go. Do not edit the file
// by hand: any change will be overwritten the next time the test runs
// with STATE_FLOW_UPDATE=1. Adjust renderHTML / htmlHeadTmpl /
// htmlTailTmpl in this file if you want to evolve the visual
// presentation.
//
// To intentionally accept a production behaviour change:
//
//	STATE_FLOW_UPDATE=1 go test ./controllers/ -run TestStateFlow_Lineages_Payloads -count=1
//
// The command (re)generates state_flow_pushed_messages.html from
// scratch. Review the diff and commit. If the file does not exist yet
// (fresh checkout, accidental deletion), the same command will create
// it; running without STATE_FLOW_UPDATE=1 against a missing file fails
// with a hint to re-run with the flag.

import (
	"context"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
	"time"

	"github.com/beclab/Olares/framework/app-service/pkg/apiserver/api"
	"github.com/beclab/Olares/framework/app-service/pkg/appstate"
	"github.com/beclab/Olares/framework/app-service/pkg/compute/validation"
	"github.com/beclab/Olares/framework/app-service/pkg/constants"
	"github.com/beclab/Olares/framework/app-service/pkg/errcode"
	appv1alpha1 "github.com/beclab/api/api/app.bytetrade.io/v1alpha1"
	"github.com/pmezard/go-difflib/difflib"

	appsv1 "k8s.io/api/apps/v1"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/types"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

// integrationReadyWorkload returns a Deployment + ready Pod pair that
// InitializingApp / ResumingApp can observe as "workload ready" via the
// fake client's label selector. The two objects are seeded into the
// controller's fake client at lineage start for lineages that drive
// through Initializing or Resuming.
func integrationReadyWorkload(name, ns string) (*appsv1.Deployment, *corev1.Pod) {
	labels := map[string]string{"app": name}
	started := true
	dep := &appsv1.Deployment{
		ObjectMeta: metav1.ObjectMeta{Name: name, Namespace: ns},
		Spec: appsv1.DeploymentSpec{
			Selector: &metav1.LabelSelector{MatchLabels: labels},
		},
	}
	pod := &corev1.Pod{
		ObjectMeta: metav1.ObjectMeta{Name: name + "-pod", Namespace: ns, Labels: labels},
		Spec:       corev1.PodSpec{Containers: []corev1.Container{{Name: "main"}}},
		Status: corev1.PodStatus{
			ContainerStatuses: []corev1.ContainerStatus{{Name: "main", Started: &started}},
		},
	}
	return dep, pod
}

// ---------------------------------------------------------------------------
// types
// ---------------------------------------------------------------------------

type driverKind int

const (
	driverReconcile driverKind = iota
	driverHandlerInstall
	driverHandlerStop
	driverHandlerResume
	driverHandlerApplyEnv
	driverHandlerUpgrade
	driverHandlerUninstall
	driverHandlerCancel
)

func (k driverKind) opLabel() appv1alpha1.OpType {
	switch k {
	case driverHandlerInstall:
		return appv1alpha1.InstallOp
	case driverHandlerStop:
		return appv1alpha1.StopOp
	case driverHandlerResume:
		return appv1alpha1.ResumeOp
	case driverHandlerApplyEnv:
		return appv1alpha1.ApplyEnvOp
	case driverHandlerUpgrade:
		return appv1alpha1.UpgradeOp
	case driverHandlerUninstall:
		return appv1alpha1.UninstallOp
	case driverHandlerCancel:
		return appv1alpha1.CancelOp
	}
	return ""
}

// lineageStep is one named step in a lineage. Each step represents a single
// transition that is observable on NATS (state + message + reason).
//
// Named lineageStep (not driver) to avoid colliding with helm's
// helm.sh/helm/v3/pkg/storage/driver package, which the controllers
// package transitively imports.
type lineageStep struct {
	// label is the transition arrow shown in the dump, e.g. "downloading->installing".
	label string
	// kind is the action that drives the transition: a Reconcile tick or
	// a specific handler write. Handler kinds also default the op recorded
	// in the dump (see opLabel) when the case otherwise leaves it implicit.
	kind driverKind
	// setup configures ctrlFakes before the step runs. Setup is cumulative
	// across steps unless explicitly reset; the previous step's leftover
	// state stays in place. May be nil.
	setup func(*ctrlFakes)
	// timeout, when true, stamps a stale Status.StatusTime onto the AM
	// before the step runs, so Reconcile's IsTimeout->Cancel branch fires.
	timeout bool
	// annotations are merged into the AM's metadata.annotations before the
	// step runs. Used for e.g. api.AppPreUpgradeStateKey.
	annotations map[string]string
	// overrideValidation, when true, swaps r.Deps.RunInstallValidation to a
	// rejecting validator for this step only.
	overrideValidation bool
	// wantState is the expected Status.State after the step completes.
	// Empty means no check (used for branches whose terminal state varies
	// or for steps that intentionally land in an unverified state).
	wantState appv1alpha1.ApplicationManagerState
}

// lineage is an ordered sequence of steps starting from <none>.
type lineage struct {
	name string
	// typ is the AM's Spec.Type used by the install handler at lineage start.
	typ appv1alpha1.Type
	// wr is the workloadReplicas hint passed to buildIntegrationAMAnnotated.
	wr bool
	// extraObjs are seeded into the fake client at lineage start.
	extraObjs []client.Object
	// steps are executed in order.
	steps []lineageStep
}

// chain concatenates a prefix slice with additional steps, producing a
// fresh slice. Use this instead of `append(prefix, more...)` directly to
// avoid Go's append-aliasing footgun when the same prefix function is
// reused across multiple lineages.
func chain(prefix []lineageStep, more ...lineageStep) []lineageStep {
	out := make([]lineageStep, 0, len(prefix)+len(more))
	out = append(out, prefix...)
	out = append(out, more...)
	return out
}

// ---------------------------------------------------------------------------
// handler simulators
// ---------------------------------------------------------------------------

// mirrorUpdateAppMgrStatus reimplements pkg/utils/app.UpdateAppMgrStatus
// against the test's fake client. It honours the production preserve-on-empty
// semantics for State / Message / Reason, plus the OpGeneration bump and
// OpRecord carry-over, so handler-driven writes that leave fields blank
// inherit them from the previous status exactly like the real apiserver
// path does.
func mirrorUpdateAppMgrStatus(t *testing.T, c client.Client, name string,
	status appv1alpha1.ApplicationManagerStatus) *appv1alpha1.ApplicationManager {
	t.Helper()
	var am appv1alpha1.ApplicationManager
	if err := c.Get(context.TODO(), types.NamespacedName{Name: name}, &am); err != nil {
		t.Fatalf("handler write: get AM %s: %v", name, err)
	}
	cur := am.DeepCopy()
	status.OpGeneration = cur.Status.OpGeneration + 1
	status.OpRecords = cur.Status.OpRecords
	if status.State == "" {
		status.State = cur.Status.State
	}
	if status.Message == "" {
		status.Message = cur.Status.Message
	}
	if status.Reason == "" {
		status.Reason = cur.Status.Reason
	}
	payload := status.Payload
	if payload == nil {
		payload = make(map[string]string)
	}
	for k, v := range cur.Status.Payload {
		if _, ok := payload[k]; !ok {
			payload[k] = v
		}
	}
	status.Payload = payload
	cur.Status = status
	// Use c.Update (whole-object) not c.Status().Update: production's
	// apputils.UpdateAppMgrStatus uses the typed clientset's Update which
	// overwrites both Spec and Status in one shot, and the controller's
	// fake client here is built WITHOUT a status subresource registration,
	// so c.Status().Update would route into an empty status tracker and
	// return NotFound. c.Update covers both subresources in this setup.
	if err := c.Update(context.TODO(), cur); err != nil {
		t.Fatalf("handler write: update AM %s: %v", name, err)
	}
	return cur
}

// updateAMSpec patches Spec.OpType (and optional annotations) before a
// handler-driven status write, mirroring the production order: spec
// Update then status Update.
func updateAMSpec(t *testing.T, c client.Client, name string,
	opType appv1alpha1.OpType, mergeAnns map[string]string) {
	t.Helper()
	var am appv1alpha1.ApplicationManager
	if err := c.Get(context.TODO(), types.NamespacedName{Name: name}, &am); err != nil {
		t.Fatalf("handler spec: get AM %s: %v", name, err)
	}
	am.Spec.OpType = opType
	if len(mergeAnns) > 0 {
		if am.Annotations == nil {
			am.Annotations = make(map[string]string)
		}
		for k, v := range mergeAnns {
			am.Annotations[k] = v
		}
	}
	if err := c.Update(context.TODO(), &am); err != nil {
		t.Fatalf("handler spec: update AM %s: %v", name, err)
	}
}

// handlerInstall mirrors pkg/apiserver/handler_installer_install.go::applyAppMgr.
// When the AM does not yet exist it Create()s it with the canonical Pending
// status; otherwise it transitions an existing terminal AM back to Pending.
func handlerInstall(t *testing.T, c client.Client, name string,
	typ appv1alpha1.Type, withWorkloadReplicas bool) *appv1alpha1.ApplicationManager {
	t.Helper()
	now := metav1.Now()
	opID := strconv.FormatInt(time.Now().UnixNano(), 10)

	var existing appv1alpha1.ApplicationManager
	err := c.Get(context.TODO(), types.NamespacedName{Name: name}, &existing)
	if err == nil {
		updateAMSpec(t, c, name, appv1alpha1.InstallOp, nil)
		return mirrorUpdateAppMgrStatus(t, c, name, appv1alpha1.ApplicationManagerStatus{
			OpType:     appv1alpha1.InstallOp,
			State:      appv1alpha1.Pending,
			OpID:       opID,
			Reason:     appv1alpha1.Pending.String(),
			Message:    "waiting for install",
			Progress:   "0.00",
			StatusTime: &now,
			UpdateTime: &now,
			OpTime:     &now,
		})
	}

	am := buildIntegrationAM(name, typ, appv1alpha1.Pending, appv1alpha1.InstallOp, withWorkloadReplicas)
	am.Status = appv1alpha1.ApplicationManagerStatus{
		OpType:     appv1alpha1.InstallOp,
		State:      appv1alpha1.Pending,
		OpID:       opID,
		Reason:     appv1alpha1.Pending.String(),
		Message:    "waiting for install",
		Progress:   "0.00",
		StatusTime: &now,
		UpdateTime: &now,
		OpTime:     &now,
	}
	if err := c.Create(context.TODO(), am); err != nil {
		t.Fatalf("handler install: create AM %s: %v", name, err)
	}
	return am
}

// handlerStop mirrors pkg/apiserver/handler_suspend.go::stopApp. Production
// writes both Message AND Reason here, so this fully overrides the prior
// Running payload.
func handlerStop(t *testing.T, c client.Client, name string) *appv1alpha1.ApplicationManager {
	t.Helper()
	var am appv1alpha1.ApplicationManager
	if err := c.Get(context.TODO(), types.NamespacedName{Name: name}, &am); err != nil {
		t.Fatalf("handler stop: get AM: %v", err)
	}
	updateAMSpec(t, c, name, appv1alpha1.StopOp, nil)
	now := metav1.Now()
	opID := strconv.FormatInt(time.Now().UnixNano(), 10)
	return mirrorUpdateAppMgrStatus(t, c, name, appv1alpha1.ApplicationManagerStatus{
		OpType:     appv1alpha1.StopOp,
		OpID:       opID,
		State:      appv1alpha1.Stopping,
		Reason:     constants.AppStopByUser,
		Message:    fmt.Sprintf("app %s was stop by user %s", am.Spec.AppName, am.Spec.AppOwner),
		StatusTime: &now,
		UpdateTime: &now,
	})
}

// handlerResume mirrors pkg/apiserver/handler_suspend.go::resumeApp.
// Production writes BOTH Message and Reason — the prior Reason from
// stopping_app / stopped is fully replaced by Reason="resuming" so the
// (state, reason) tuple stays in sync per the "reason = target state
// name" convention enforced across the rest of the lifecycle.
func handlerResume(t *testing.T, c client.Client, name string) *appv1alpha1.ApplicationManager {
	t.Helper()
	var am appv1alpha1.ApplicationManager
	if err := c.Get(context.TODO(), types.NamespacedName{Name: name}, &am); err != nil {
		t.Fatalf("handler resume: get AM: %v", err)
	}
	updateAMSpec(t, c, name, appv1alpha1.ResumeOp, nil)
	now := metav1.Now()
	opID := strconv.FormatInt(time.Now().UnixNano(), 10)
	return mirrorUpdateAppMgrStatus(t, c, name, appv1alpha1.ApplicationManagerStatus{
		OpType:     appv1alpha1.ResumeOp,
		OpID:       opID,
		State:      appv1alpha1.Resuming,
		Message:    fmt.Sprintf("app %s was resume by user %s", am.Spec.AppName, am.Spec.AppOwner),
		Reason:     appv1alpha1.Resuming.String(),
		StatusTime: &now,
		UpdateTime: &now,
	})
}

// handlerApplyEnv mirrors pkg/apiserver/handler_applyenv.go. Production
// writes only Message; Reason is preserved from the prior Running push.
func handlerApplyEnv(t *testing.T, c client.Client, name string) *appv1alpha1.ApplicationManager {
	t.Helper()
	updateAMSpec(t, c, name, appv1alpha1.ApplyEnvOp, nil)
	now := metav1.Now()
	opID := strconv.FormatInt(time.Now().UnixNano(), 10)
	return mirrorUpdateAppMgrStatus(t, c, name, appv1alpha1.ApplicationManagerStatus{
		OpType:     appv1alpha1.ApplyEnvOp,
		OpID:       opID,
		State:      appv1alpha1.ApplyingEnv,
		Message:    "waiting for applying env",
		StatusTime: &now,
		UpdateTime: &now,
	})
}

// handlerUpgrade mirrors pkg/apiserver/handler_installer_upgrade.go.
// Production writes BOTH Message and Reason — Reason="upgrading"
// fully replaces the prior Reason (typically running's "running") so
// the (state, reason) tuple stays in sync.
//
// NOTE: handler_settings.go's setup-domain entry point ALSO triggers
// an UpgradeOp but only writes Message (no Reason), inconsistent with
// the main upgrade handler. No lineage covers that secondary path; if
// one is added later the simulator will need to model that variant.
func handlerUpgrade(t *testing.T, c client.Client, name string) *appv1alpha1.ApplicationManager {
	t.Helper()
	var am appv1alpha1.ApplicationManager
	if err := c.Get(context.TODO(), types.NamespacedName{Name: name}, &am); err != nil {
		t.Fatalf("handler upgrade: get AM: %v", err)
	}
	updateAMSpec(t, c, name, appv1alpha1.UpgradeOp, nil)
	now := metav1.Now()
	opID := strconv.FormatInt(time.Now().UnixNano(), 10)
	return mirrorUpdateAppMgrStatus(t, c, name, appv1alpha1.ApplicationManagerStatus{
		OpType:     appv1alpha1.UpgradeOp,
		OpID:       opID,
		State:      appv1alpha1.Upgrading,
		Message:    fmt.Sprintf("app %s was upgrade by user %s", am.Spec.AppName, am.Spec.AppOwner),
		Reason:     appv1alpha1.Upgrading.String(),
		StatusTime: &now,
		UpdateTime: &now,
	})
}

// handlerUninstall mirrors pkg/apiserver/handler_installer_uninstall.go.
// Production writes BOTH Message="start to uninstall" and
// Reason="uninstalling", fully overriding whatever the prior state
// pushed (Running's "running"/"running", InstallFailed's
// "<err>"/"installFailed", etc.). The dump therefore must show a
// uniform (message, reason) tuple for every *->uninstalling step.
func handlerUninstall(t *testing.T, c client.Client, name string) *appv1alpha1.ApplicationManager {
	t.Helper()
	updateAMSpec(t, c, name, appv1alpha1.UninstallOp, nil)
	now := metav1.Now()
	opID := strconv.FormatInt(time.Now().UnixNano(), 10)
	return mirrorUpdateAppMgrStatus(t, c, name, appv1alpha1.ApplicationManagerStatus{
		OpType:     appv1alpha1.UninstallOp,
		OpID:       opID,
		State:      appv1alpha1.Uninstalling,
		Message:    "start to uninstall",
		Reason:     appv1alpha1.Uninstalling.String(),
		Progress:   "0.00",
		StatusTime: &now,
		UpdateTime: &now,
	})
}

// handlerCancel mirrors pkg/apiserver/handler_installer_cancel.go::cancel,
// modelling the user-initiated cancel path. Production:
//   - resolves the target *Canceling state via a switch on the current
//     Status.State (Pending/Downloading/Installing/Initializing/Resuming/
//     Upgrading/ApplyingEnv → corresponding *Canceling state);
//   - flips Spec.OpType to CancelOp;
//   - writes (Message, Reason) via cancelStatus(cancelType, cancelState).
//     Message is a human-readable per-operation phrase ("Install canceled.
//     Operation by user." etc.) parallel to the constants.<X>CanceledByTimeout
//     wording the reconcile/IsTimeout path uses; Reason is a stable
//     camelCase tag ("installCancelByUser" / "upgradeCancelByUser" etc.)
//     so consumers can branch without parsing the message sentence.
//     finishCancelToStopping then propagates both fields into Stopping
//     via updateStatus's preserve-on-empty Reason semantics.
//
// We exercise cancelType="operate" because that's the implicit default
// (no ?type= query string) and the only call site present in the repo's
// dashboard/CLI code. If a lineage ever needs to exercise the
// ?type=timeout user-cancel variant we'll add an overload; today only
// the operate case is covered.
func handlerCancel(t *testing.T, c client.Client, name string) *appv1alpha1.ApplicationManager {
	t.Helper()
	var am appv1alpha1.ApplicationManager
	if err := c.Get(context.TODO(), types.NamespacedName{Name: name}, &am); err != nil {
		t.Fatalf("handler cancel: get AM: %v", err)
	}
	var cancelState appv1alpha1.ApplicationManagerState
	switch am.Status.State {
	case appv1alpha1.Pending, appv1alpha1.PendingCancelFailed:
		cancelState = appv1alpha1.PendingCanceling
	case appv1alpha1.Downloading, appv1alpha1.DownloadingCancelFailed:
		cancelState = appv1alpha1.DownloadingCanceling
	case appv1alpha1.Installing, appv1alpha1.InstallingCancelFailed:
		cancelState = appv1alpha1.InstallingCanceling
	case appv1alpha1.Initializing:
		cancelState = appv1alpha1.InitializingCanceling
	case appv1alpha1.Resuming:
		cancelState = appv1alpha1.ResumingCanceling
	case appv1alpha1.Upgrading:
		cancelState = appv1alpha1.UpgradingCanceling
	case appv1alpha1.ApplyingEnv:
		cancelState = appv1alpha1.ApplyingEnvCanceling
	default:
		t.Fatalf("handler cancel: state %q is not cancelable", am.Status.State)
	}
	updateAMSpec(t, c, name, appv1alpha1.CancelOp, nil)
	now := metav1.Now()
	opID := strconv.FormatInt(time.Now().UnixNano(), 10)
	cancelMsg, cancelReason := mirrorCancelStatus("operate", cancelState)
	return mirrorUpdateAppMgrStatus(t, c, name, appv1alpha1.ApplicationManagerStatus{
		OpType:     appv1alpha1.CancelOp,
		OpID:       opID,
		LastState:  am.Status.LastState,
		State:      cancelState,
		Progress:   "0.00",
		Message:    cancelMsg,
		Reason:     cancelReason,
		StatusTime: &now,
		UpdateTime: &now,
	})
}

// mirrorCancelStatus MUST stay in lockstep with cancelStatus in
// pkg/apiserver/handler_installer_cancel.go. Drift will surface as a
// dump mismatch in TestStateFlow_Lineages_Payloads — but we still
// duplicate the logic (instead of importing handler internals into a
// test) because the apiserver package depends on controller-runtime
// machinery that the lineage harness intentionally side-steps via
// fakeDeps and the in-memory fake client.
func mirrorCancelStatus(cancelType string, cancelState appv1alpha1.ApplicationManagerState) (message, reason string) {
	isTimeout := cancelType == "timeout"
	switch cancelState {
	case appv1alpha1.PendingCanceling, appv1alpha1.InstallingCanceling:
		if isTimeout {
			return constants.InstallCanceledByTimeout, constants.InstallCancelBySystem
		}
		return constants.InstallCanceledByUser, constants.InstallCancelByUser
	case appv1alpha1.DownloadingCanceling:
		if isTimeout {
			return constants.DownloadCanceledByTimeout, constants.DownloadCancelBySystem
		}
		return constants.DownloadCanceledByUser, constants.DownloadCancelByUser
	case appv1alpha1.InitializingCanceling:
		if isTimeout {
			return constants.InitializeCanceledByTimeout, constants.InitializeCancelBySystem
		}
		return constants.InitializeCanceledByUser, constants.InitializeCancelByUser
	case appv1alpha1.ResumingCanceling:
		if isTimeout {
			return constants.ResumeCanceledByTimeout, constants.ResumeCancelBySystem
		}
		return constants.ResumeCanceledByUser, constants.ResumeCancelByUser
	case appv1alpha1.UpgradingCanceling:
		if isTimeout {
			return constants.UpgradeCanceledByTimeout, constants.UpgradeCancelBySystem
		}
		return constants.UpgradeCanceledByUser, constants.UpgradeCancelByUser
	case appv1alpha1.ApplyingEnvCanceling:
		if isTimeout {
			return constants.ApplyEnvCanceledByTimeout, constants.ApplyEnvCancelBySystem
		}
		return constants.ApplyEnvCanceledByUser, constants.ApplyEnvCancelByUser
	}
	return cancelType, cancelState.String()
}

// ---------------------------------------------------------------------------
// runner helpers
// ---------------------------------------------------------------------------

// applyTimeoutToAM stamps a stale Status.StatusTime onto the AM so the
// next Reconcile sees operation.IsTimeout() == true and routes into the
// Cancel branch.
func applyTimeoutToAM(t *testing.T, c client.Client, name string) {
	t.Helper()
	var am appv1alpha1.ApplicationManager
	if err := c.Get(context.TODO(), types.NamespacedName{Name: name}, &am); err != nil {
		t.Fatalf("apply timeout: get AM: %v", err)
	}
	past := metav1.NewTime(time.Now().Add(-240 * time.Hour))
	am.Status.StatusTime = &past
	if err := c.Update(context.TODO(), &am); err != nil {
		t.Fatalf("apply timeout: update AM: %v", err)
	}
}

func mergeAMAnnotations(t *testing.T, c client.Client, name string, kv map[string]string) {
	t.Helper()
	if len(kv) == 0 {
		return
	}
	var am appv1alpha1.ApplicationManager
	if err := c.Get(context.TODO(), types.NamespacedName{Name: name}, &am); err != nil {
		t.Fatalf("merge annotations: get AM: %v", err)
	}
	if am.Annotations == nil {
		am.Annotations = make(map[string]string)
	}
	for k, v := range kv {
		am.Annotations[k] = v
	}
	if err := c.Update(context.TODO(), &am); err != nil {
		t.Fatalf("merge annotations: update AM: %v", err)
	}
}

// ---------------------------------------------------------------------------
// dump recorder
// ---------------------------------------------------------------------------

type dumpRow struct {
	lineage string
	step    int
	label   string
	op      appv1alpha1.OpType
	state   appv1alpha1.ApplicationManagerState
	message string
	reason  string
}

type dumpRecorder struct {
	rows []dumpRow
}

func (rec *dumpRecorder) add(lineageName string, step int, label string,
	am *appv1alpha1.ApplicationManager) {
	rec.rows = append(rec.rows, dumpRow{
		lineage: lineageName,
		step:    step,
		label:   label,
		op:      am.Status.OpType,
		state:   am.Status.State,
		message: am.Status.Message,
		reason:  am.Status.Reason,
	})
}

// renderPerLineage emits one section per lineage, in declaration order,
// showing every transition in execution order. Repeated transitions
// across lineages are intentionally not deduped here — each lineage tells
// a complete story.
func (rec *dumpRecorder) renderPerLineage(lineages []lineage) string {
	idx := map[string][]dumpRow{}
	for _, r := range rec.rows {
		idx[r.lineage] = append(idx[r.lineage], r)
	}
	var sb strings.Builder
	fmt.Fprintf(&sb, "==================== LINEAGE-DRIVEN PUSHED MESSAGES ====================\n")
	fmt.Fprintf(&sb, "Each lineage starts at <none> and drives the AM through the production\n")
	fmt.Fprintf(&sb, "state machine via handler writes + Reconcile ticks. The (state, op,\n")
	fmt.Fprintf(&sb, "message, reason) tuple after every step is captured below.\n")
	fmt.Fprintf(&sb, "========================================================================\n\n")
	for _, l := range lineages {
		rows := idx[l.name]
		if len(rows) == 0 {
			continue
		}
		fmt.Fprintf(&sb, "------ lineage: %s (typ=%s, wr=%t) ------\n", l.name, l.typ, l.wr)
		for _, r := range rows {
			fmt.Fprintf(&sb, "  [%d] %-50s -> state=%-22s op=%-10s\n",
				r.step, r.label, r.state, r.op)
			fmt.Fprintf(&sb, "        message = %q\n", r.message)
			fmt.Fprintf(&sb, "        reason  = %q\n", r.reason)
		}
		fmt.Fprintln(&sb)
	}
	return sb.String()
}

// ---------------------------------------------------------------------------
// runLineage
// ---------------------------------------------------------------------------

func runLineage(t *testing.T, l lineage, rec *dumpRecorder) {
	t.Helper()
	r, f := newTestController(t, l.extraObjs...)
	const name = "demo"

	for i, d := range l.steps {
		if d.annotations != nil {
			mergeAMAnnotations(t, r.Client, name, d.annotations)
		}
		if d.timeout {
			applyTimeoutToAM(t, r.Client, name)
		}
		if d.setup != nil {
			d.setup(f)
		}
		if d.overrideValidation {
			r.Deps.RunInstallValidation = func(ctx context.Context, in validation.Input) (validation.Decision, error) {
				return validation.Decision{OK: false, Validator: "k8s-request", Message: "insufficient memory"}, nil
			}
		}

		var observed *appv1alpha1.ApplicationManager
		switch d.kind {
		case driverHandlerInstall:
			observed = handlerInstall(t, r.Client, name, l.typ, l.wr)
		case driverHandlerStop:
			observed = handlerStop(t, r.Client, name)
		case driverHandlerResume:
			observed = handlerResume(t, r.Client, name)
		case driverHandlerApplyEnv:
			observed = handlerApplyEnv(t, r.Client, name)
		case driverHandlerUpgrade:
			observed = handlerUpgrade(t, r.Client, name)
		case driverHandlerUninstall:
			observed = handlerUninstall(t, r.Client, name)
		case driverHandlerCancel:
			observed = handlerCancel(t, r.Client, name)
		case driverReconcile:
			doReconcile(t, r, name)
			if d.wantState != "" {
				waitForState(t, r.Client, name, d.wantState, 8*time.Second)
			}
			var fresh appv1alpha1.ApplicationManager
			if err := r.Client.Get(context.TODO(), types.NamespacedName{Name: name}, &fresh); err != nil {
				t.Fatalf("lineage %s step %d %s: get AM: %v", l.name, i, d.label, err)
			}
			observed = &fresh
		}

		if d.kind != driverReconcile && d.wantState != "" && observed.Status.State != d.wantState {
			t.Fatalf("lineage %s step %d %s: wantState=%s got=%s",
				l.name, i, d.label, d.wantState, observed.Status.State)
		}

		rec.add(l.name, i, d.label, observed)
	}
}

// ---------------------------------------------------------------------------
// prefix helpers (shared lineage segments)
// ---------------------------------------------------------------------------

// driveToPending: <none> -> handler/install -> Pending.
func driveToPending() []lineageStep {
	return []lineageStep{
		{label: "<none>->pending", kind: driverHandlerInstall, wantState: appv1alpha1.Pending},
	}
}

// driveToDownloading: ... -> Downloading.
func driveToDownloading() []lineageStep {
	return chain(driveToPending(), lineageStep{
		label: "pending->downloading", kind: driverReconcile, wantState: appv1alpha1.Downloading,
	})
}

// driveToInstalling: ... -> Installing.
func driveToInstalling() []lineageStep {
	return chain(driveToDownloading(), lineageStep{
		label: "downloading->installing", kind: driverReconcile, wantState: appv1alpha1.Installing,
	})
}

// driveToInitializing: ... -> Initializing.
func driveToInitializing() []lineageStep {
	return chain(driveToInstalling(), lineageStep{
		label: "installing->initializing", kind: driverReconcile, wantState: appv1alpha1.Initializing,
	})
}

// driveToRunning: ... -> Running. The integration workload (dep+pod) is
// seeded at lineage start; without it InitializingApp would block.
func driveToRunning() []lineageStep {
	return chain(driveToInitializing(), lineageStep{
		label: "initializing->running", kind: driverReconcile, wantState: appv1alpha1.Running,
	})
}

// ---------------------------------------------------------------------------
// lineage definitions
// ---------------------------------------------------------------------------

func allLineages() []lineage {
	dep, pod := integrationReadyWorkload("demo", "demo-ns")
	workload := []client.Object{dep, pod}

	return []lineage{
		// ============ INSTALL HAPPY PATHS ============
		{
			name: "install-app-happy", typ: appv1alpha1.App, extraObjs: workload,
			steps: driveToRunning(),
		},
		{
			name: "install-middleware-happy", typ: appv1alpha1.Middleware,
			steps: chain(driveToInstalling(), lineageStep{
				label: "installing->running", kind: driverReconcile, wantState: appv1alpha1.Running,
			}),
		},

		// ============ INSTALL FAILURES (with handler retry) ============
		{
			name: "install-fail-download-retry", typ: appv1alpha1.App,
			steps: chain(driveToDownloading(),
				lineageStep{
					label: "downloading->downloadFailed", kind: driverReconcile,
					setup:     func(f *ctrlFakes) { f.img.pollErr = errors.New("pull failed") },
					wantState: appv1alpha1.DownloadFailed,
				},
				lineageStep{label: "downloadFailed->pending", kind: driverHandlerInstall, wantState: appv1alpha1.Pending},
			),
		},
		{
			name: "install-fail-helm-retry", typ: appv1alpha1.App,
			steps: chain(driveToInstalling(),
				lineageStep{
					label: "installing->installFailed", kind: driverReconcile,
					setup:     func(f *ctrlFakes) { f.helm.installErr = errors.New("boom") },
					wantState: appv1alpha1.InstallFailed,
				},
				lineageStep{label: "installFailed->pending", kind: driverHandlerInstall, wantState: appv1alpha1.Pending},
			),
		},
		{
			name: "install-fail-validation", typ: appv1alpha1.App,
			steps: chain(driveToInstalling(), lineageStep{
				label: "installing->installFailed-validation", kind: driverReconcile,
				overrideValidation: true, wantState: appv1alpha1.InstallFailed,
			}),
		},

		// ============ POST-INSTALL pod-pending forks (Installing -> Stopping) ============
		{
			// Generic (non-pod-pending) WaitForStartUp failure path. Keep the
			// fake's error text *unrelated* to pod-pending semantics so the
			// dump's (message, reason) tuple stays self-consistent:
			//   reason="StartUpFailed" must NOT be paired with a message that
			//   reads like "pod is pending" — production reserves the
			//   Unschedulable/HamiUnschedulable reasons for the
			//   ErrPodPending / ErrServerSidePodPending / ErrHamiUnschedulable
			//   sentinels (see installing_app.go's WaitForStartUp branch). The
			//   dedicated install-stopping-{pod,serverSidePod,hami}* lineages
			//   below cover those sentinels.
			name: "install-stopping-startup", typ: appv1alpha1.App,
			steps: chain(driveToInstalling(), lineageStep{
				label: "installing->stopping", kind: driverReconcile,
				setup: func(f *ctrlFakes) {
					f.helm.waitForStartUp = func() (bool, error) {
						return false, errors.New("deployment never became ready")
					}
				},
				wantState: appv1alpha1.Stopping,
			}),
		},
		{
			name: "install-stopping-podPending", typ: appv1alpha1.App,
			steps: chain(driveToInstalling(), lineageStep{
				label: "installing->stopping-podPending", kind: driverReconcile,
				setup:     func(f *ctrlFakes) { f.helm.installErr = errcode.ErrPodPending },
				wantState: appv1alpha1.Stopping,
			}),
		},
		{
			name: "install-stopping-serverSidePodPending", typ: appv1alpha1.App,
			steps: chain(driveToInstalling(), lineageStep{
				label: "installing->stopping-serverSidePodPending", kind: driverReconcile,
				setup:     func(f *ctrlFakes) { f.helm.installErr = errcode.ErrServerSidePodPending },
				wantState: appv1alpha1.Stopping,
			}),
		},
		{
			name: "install-stopping-hamiUnschedulable", typ: appv1alpha1.App,
			steps: chain(driveToInstalling(), lineageStep{
				label: "installing->stopping-hamiUnschedulable", kind: driverReconcile,
				setup: func(f *ctrlFakes) {
					f.helm.installErr = errors.Join(errcode.ErrPodPending, errcode.ErrHamiUnschedulable)
				},
				wantState: appv1alpha1.Stopping,
			}),
		},

		// ============ CANCEL via TIMEOUT (with handler retry where applicable) ============
		{
			name: "cancel-pending-retry", typ: appv1alpha1.App,
			steps: chain(driveToPending(),
				lineageStep{label: "pending->pendingCanceling", kind: driverReconcile, timeout: true, wantState: appv1alpha1.PendingCanceling},
				lineageStep{label: "pendingCanceling->pendingCanceled", kind: driverReconcile, wantState: appv1alpha1.PendingCanceled},
				lineageStep{label: "pendingCanceled->pending", kind: driverHandlerInstall, wantState: appv1alpha1.Pending},
			),
		},
		{
			name: "cancel-downloading-retry", typ: appv1alpha1.App,
			steps: chain(driveToDownloading(),
				lineageStep{label: "downloading->downloadingCanceling", kind: driverReconcile, timeout: true, wantState: appv1alpha1.DownloadingCanceling},
				lineageStep{label: "downloadingCanceling->downloadingCanceled", kind: driverReconcile, wantState: appv1alpha1.DownloadingCanceled},
				lineageStep{label: "downloadingCanceled->pending", kind: driverHandlerInstall, wantState: appv1alpha1.Pending},
			),
		},
		{
			name: "cancel-downloading-fail", typ: appv1alpha1.App,
			steps: chain(driveToDownloading(),
				lineageStep{label: "downloading->downloadingCanceling", kind: driverReconcile, timeout: true, wantState: appv1alpha1.DownloadingCanceling},
				lineageStep{
					label: "downloadingCanceling->downloadingCancelFailed", kind: driverReconcile,
					setup:     func(f *ctrlFakes) { f.img.updateStatusErr = errors.New("im update failed") },
					wantState: appv1alpha1.DownloadingCancelFailed,
				},
			),
		},
		{
			name: "cancel-installing-retry", typ: appv1alpha1.App,
			steps: chain(driveToInstalling(),
				lineageStep{label: "installing->installingCanceling", kind: driverReconcile, timeout: true, wantState: appv1alpha1.InstallingCanceling},
				lineageStep{label: "installingCanceling->installingCanceled", kind: driverReconcile, wantState: appv1alpha1.InstallingCanceled},
				lineageStep{label: "installingCanceled->pending", kind: driverHandlerInstall, wantState: appv1alpha1.Pending},
			),
		},
		{
			name: "cancel-installing-fail", typ: appv1alpha1.App,
			steps: chain(driveToInstalling(),
				lineageStep{label: "installing->installingCanceling", kind: driverReconcile, timeout: true, wantState: appv1alpha1.InstallingCanceling},
				lineageStep{
					label: "installingCanceling->installingCancelFailed", kind: driverReconcile,
					setup:     func(f *ctrlFakes) { f.helm.uninstallErr = errors.New("boom") },
					wantState: appv1alpha1.InstallingCancelFailed,
				},
			),
		},
		{
			name: "cancel-initializing-timeout", typ: appv1alpha1.App, extraObjs: workload,
			steps: chain(driveToInitializing(),
				lineageStep{label: "initializing->initializingCanceling", kind: driverReconcile, timeout: true, wantState: appv1alpha1.InitializingCanceling},
				lineageStep{label: "initializingCanceling->stopping", kind: driverReconcile, wantState: appv1alpha1.Stopping},
			),
		},
		{
			name: "init-fail-launch", typ: appv1alpha1.App, extraObjs: workload,
			steps: chain(driveToInitializing(),
				lineageStep{
					label: "initializing->initializingCanceling", kind: driverReconcile,
					setup: func(f *ctrlFakes) {
						f.helm.waitForLaunch = func() (bool, error) { return false, errors.New("launch failed") }
					},
					wantState: appv1alpha1.InitializingCanceling,
				},
				lineageStep{label: "initializingCanceling->stopping", kind: driverReconcile, wantState: appv1alpha1.Stopping},
			),
		},

		// ============ USER-INITIATED CANCEL (handler-driven) ============
		// These mirror the timeout-driven cancel lineages above but exercise
		// pkg/apiserver/handler_installer_cancel.go::cancel instead of the
		// IsTimeout()/Reconcile path. Production writes Message=cancelType
		// ("operate") and preserves Reason from the source state, so the
		// dump's [*->*Canceling] step shows ("operate", <source-state>) —
		// distinct from the timeout-cancel tuple ("<X> canceled. Operation
		// timed out.", "<X>Canceling") and visible as a separate row in the
		// unique-transition coverage section.
		{
			name: "user-cancel-pending", typ: appv1alpha1.App,
			steps: chain(driveToPending(),
				lineageStep{label: "pending->pendingCanceling", kind: driverHandlerCancel, wantState: appv1alpha1.PendingCanceling},
				lineageStep{label: "pendingCanceling->pendingCanceled", kind: driverReconcile, wantState: appv1alpha1.PendingCanceled},
				lineageStep{label: "pendingCanceled->pending", kind: driverHandlerInstall, wantState: appv1alpha1.Pending},
			),
		},
		{
			name: "user-cancel-downloading", typ: appv1alpha1.App,
			steps: chain(driveToDownloading(),
				lineageStep{label: "downloading->downloadingCanceling", kind: driverHandlerCancel, wantState: appv1alpha1.DownloadingCanceling},
				lineageStep{label: "downloadingCanceling->downloadingCanceled", kind: driverReconcile, wantState: appv1alpha1.DownloadingCanceled},
				lineageStep{label: "downloadingCanceled->pending", kind: driverHandlerInstall, wantState: appv1alpha1.Pending},
			),
		},
		{
			name: "user-cancel-installing", typ: appv1alpha1.App,
			steps: chain(driveToInstalling(),
				lineageStep{label: "installing->installingCanceling", kind: driverHandlerCancel, wantState: appv1alpha1.InstallingCanceling},
				lineageStep{label: "installingCanceling->installingCanceled", kind: driverReconcile, wantState: appv1alpha1.InstallingCanceled},
				lineageStep{label: "installingCanceled->pending", kind: driverHandlerInstall, wantState: appv1alpha1.Pending},
			),
		},
		{
			name: "user-cancel-initializing", typ: appv1alpha1.App, extraObjs: workload,
			steps: chain(driveToInitializing(),
				lineageStep{label: "initializing->initializingCanceling", kind: driverHandlerCancel, wantState: appv1alpha1.InitializingCanceling},
				lineageStep{label: "initializingCanceling->stopping", kind: driverReconcile, wantState: appv1alpha1.Stopping},
			),
		},
		{
			name: "user-cancel-resuming", typ: appv1alpha1.App, extraObjs: workload,
			steps: chain(driveToRunning(),
				lineageStep{label: "running->stopping", kind: driverHandlerStop, wantState: appv1alpha1.Stopping},
				lineageStep{label: "stopping->stopped", kind: driverReconcile, wantState: appv1alpha1.Stopped},
				lineageStep{label: "stopped->resuming", kind: driverHandlerResume, wantState: appv1alpha1.Resuming},
				lineageStep{label: "resuming->resumingCanceling", kind: driverHandlerCancel, wantState: appv1alpha1.ResumingCanceling},
				lineageStep{label: "resumingCanceling->stopping", kind: driverReconcile, wantState: appv1alpha1.Stopping},
			),
		},
		{
			name: "user-cancel-applyingEnv", typ: appv1alpha1.App, extraObjs: workload,
			steps: chain(driveToRunning(),
				lineageStep{label: "running->applyingEnv", kind: driverHandlerApplyEnv, wantState: appv1alpha1.ApplyingEnv},
				lineageStep{label: "applyingEnv->applyingEnvCanceling", kind: driverHandlerCancel, wantState: appv1alpha1.ApplyingEnvCanceling},
				lineageStep{label: "applyingEnvCanceling->stopping", kind: driverReconcile, wantState: appv1alpha1.Stopping},
			),
		},
		{
			name: "user-cancel-upgrading", typ: appv1alpha1.App, extraObjs: workload,
			steps: chain(driveToRunning(),
				lineageStep{label: "running->upgrading", kind: driverHandlerUpgrade, wantState: appv1alpha1.Upgrading},
				lineageStep{label: "upgrading->upgradingCanceling", kind: driverHandlerCancel, wantState: appv1alpha1.UpgradingCanceling},
				lineageStep{label: "upgradingCanceling->stopping", kind: driverReconcile, wantState: appv1alpha1.Stopping},
			),
		},

		// ============ STOP / RESUME / APPLYENV / UPGRADE / UNINSTALL (require Running) ============
		{
			name: "stop-success-resume", typ: appv1alpha1.App, extraObjs: workload,
			steps: chain(driveToRunning(),
				lineageStep{label: "running->stopping", kind: driverHandlerStop, wantState: appv1alpha1.Stopping},
				lineageStep{label: "stopping->stopped", kind: driverReconcile, wantState: appv1alpha1.Stopped},
				lineageStep{label: "stopped->resuming", kind: driverHandlerResume, wantState: appv1alpha1.Resuming},
				lineageStep{label: "resuming->initializing", kind: driverReconcile, wantState: appv1alpha1.Initializing},
				lineageStep{label: "initializing->running-resume", kind: driverReconcile, wantState: appv1alpha1.Running},
			),
		},
		{
			name: "stop-fail", typ: appv1alpha1.App, wr: true, extraObjs: workload,
			steps: chain(driveToRunning(),
				lineageStep{label: "running->stopping", kind: driverHandlerStop, wantState: appv1alpha1.Stopping},
				lineageStep{
					label: "stopping->stopFailed", kind: driverReconcile,
					setup:     func(f *ctrlFakes) { f.helm.scaleErr = errors.New("boom") },
					wantState: appv1alpha1.StopFailed,
				},
			),
		},
		{
			name: "resume-fail", typ: appv1alpha1.App, wr: true, extraObjs: workload,
			steps: chain(driveToRunning(),
				lineageStep{label: "running->stopping", kind: driverHandlerStop, wantState: appv1alpha1.Stopping},
				lineageStep{label: "stopping->stopped", kind: driverReconcile, wantState: appv1alpha1.Stopped},
				lineageStep{label: "stopped->resuming", kind: driverHandlerResume, wantState: appv1alpha1.Resuming},
				lineageStep{
					label: "resuming->resumeFailed", kind: driverReconcile,
					setup:     func(f *ctrlFakes) { f.helm.scaleErr = errors.New("boom") },
					wantState: appv1alpha1.ResumeFailed,
				},
			),
		},
		{
			name: "resume-cancel", typ: appv1alpha1.App, extraObjs: workload,
			steps: chain(driveToRunning(),
				lineageStep{label: "running->stopping", kind: driverHandlerStop, wantState: appv1alpha1.Stopping},
				lineageStep{label: "stopping->stopped", kind: driverReconcile, wantState: appv1alpha1.Stopped},
				lineageStep{label: "stopped->resuming", kind: driverHandlerResume, wantState: appv1alpha1.Resuming},
				lineageStep{label: "resuming->resumingCanceling", kind: driverReconcile, timeout: true, wantState: appv1alpha1.ResumingCanceling},
				lineageStep{label: "resumingCanceling->stopping", kind: driverReconcile, wantState: appv1alpha1.Stopping},
			),
		},
		{
			name: "applyEnv-success", typ: appv1alpha1.App, extraObjs: workload,
			steps: chain(driveToRunning(),
				lineageStep{label: "running->applyingEnv", kind: driverHandlerApplyEnv, wantState: appv1alpha1.ApplyingEnv},
				lineageStep{label: "applyingEnv->initializing", kind: driverReconcile, wantState: appv1alpha1.Initializing},
				lineageStep{label: "initializing->running-applyEnv", kind: driverReconcile, wantState: appv1alpha1.Running},
			),
		},
		{
			name: "applyEnv-fail", typ: appv1alpha1.App, extraObjs: workload,
			steps: chain(driveToRunning(),
				lineageStep{label: "running->applyingEnv", kind: driverHandlerApplyEnv, wantState: appv1alpha1.ApplyingEnv},
				lineageStep{
					label: "applyingEnv->applyEnvFailed", kind: driverReconcile,
					setup:     func(f *ctrlFakes) { f.helm.applyEnvErr = errors.New("boom") },
					wantState: appv1alpha1.ApplyEnvFailed,
				},
			),
		},
		{
			name: "applyEnv-cancel", typ: appv1alpha1.App, extraObjs: workload,
			steps: chain(driveToRunning(),
				lineageStep{label: "running->applyingEnv", kind: driverHandlerApplyEnv, wantState: appv1alpha1.ApplyingEnv},
				lineageStep{label: "applyingEnv->applyingEnvCanceling", kind: driverReconcile, timeout: true, wantState: appv1alpha1.ApplyingEnvCanceling},
				lineageStep{label: "applyingEnvCanceling->stopping", kind: driverReconcile, wantState: appv1alpha1.Stopping},
			),
		},
		{
			// Happy upgrade path (upgrading->initializing/stopped/upgradeFailed) is
			// blocked on the UpgradingApp seam refactor and intentionally NOT modelled
			// here. The timeout-driven cancel works because Reconcile.Cancel fires
			// before NewUpgradingApp is constructed.
			name: "upgrade-cancel", typ: appv1alpha1.App, extraObjs: workload,
			steps: chain(driveToRunning(),
				lineageStep{label: "running->upgrading", kind: driverHandlerUpgrade, wantState: appv1alpha1.Upgrading},
				lineageStep{label: "upgrading->upgradingCanceling", kind: driverReconcile, timeout: true, wantState: appv1alpha1.UpgradingCanceling},
				lineageStep{label: "upgradingCanceling->stopping", kind: driverReconcile, wantState: appv1alpha1.Stopping},
			),
		},

		// ============ UNINSTALL ============
		{
			name: "uninstall-success-retry", typ: appv1alpha1.App, extraObjs: workload,
			steps: chain(driveToRunning(),
				lineageStep{label: "running->uninstalling", kind: driverHandlerUninstall, wantState: appv1alpha1.Uninstalling},
				lineageStep{label: "uninstalling->uninstalled", kind: driverReconcile, wantState: appv1alpha1.Uninstalled},
				lineageStep{label: "uninstalled->pending", kind: driverHandlerInstall, wantState: appv1alpha1.Pending},
			),
		},
		{
			name: "uninstall-fail-then-self-heal", typ: appv1alpha1.App, extraObjs: workload,
			steps: chain(driveToRunning(),
				lineageStep{label: "running->uninstalling", kind: driverHandlerUninstall, wantState: appv1alpha1.Uninstalling},
				lineageStep{
					label: "uninstalling->uninstallFailed", kind: driverReconcile,
					setup:     func(f *ctrlFakes) { f.helm.uninstallErr = errors.New("boom") },
					wantState: appv1alpha1.UninstallFailed,
				},
				lineageStep{
					label: "uninstallFailed->uninstalled-self-heal", kind: driverReconcile,
					setup:     func(f *ctrlFakes) { f.helm.uninstallErr = nil },
					wantState: appv1alpha1.Uninstalled,
				},
			),
		},

		// ============ RUNNING -> UNINSTALLED self-heal (no Application sibling) ============
		{
			// initializing->running uses InitializingApp.Exec, which writes
			// Running based on workload-readiness, NOT on the Application
			// sibling. The next reconcile constructs NewRunningApp, which
			// DOES look for the Application sibling; finding none, it
			// self-heals via forceDeleteApp + updateStatus(Uninstalled).
			name: "running-self-heal-uninstall", typ: appv1alpha1.App, extraObjs: workload,
			steps: chain(driveToRunning(), lineageStep{
				label: "running->uninstalled-self-heal", kind: driverReconcile,
				wantState: appv1alpha1.Uninstalled,
			}),
		},

		// ============ UPGRADE OpType pass-through (initializing->running with OpType=Upgrade) ============
		// initializing->running-upgrade has the same Reconcile path as
		// initializing->running but with OpType=Upgrade carried through
		// from the upgrade handler. Modelled separately with a synthetic
		// upgrade prefix until the UpgradingApp seam refactor unblocks
		// the full happy path.
		{
			name: "initializing-from-upgrade-stub", typ: appv1alpha1.App, wr: true, extraObjs: workload,
			steps: chain(driveToInitializing(),
				// Force-set OpType=Upgrade via annotation+spec patch
				// (mirrors what the upgrade handler does before the
				// happy path returns to Initializing). The reconcile
				// then drives initializing->running with op=upgrade.
				lineageStep{
					label: "initializing->running-upgrade", kind: driverReconcile,
					setup: func(f *ctrlFakes) {
						// no fake config needed; the OpType swap happens via
						// the annotations field below.
					},
					annotations: map[string]string{api.AppPreUpgradeStateKey: appv1alpha1.Stopped.String()},
					wantState:   appv1alpha1.Running,
				},
			),
		},
	}
}

// ---------------------------------------------------------------------------
// tests
// ---------------------------------------------------------------------------

const lineageHTMLPath = "state_flow_pushed_messages.html"

// TestStateFlow_Lineages_Payloads drives every lineage in allLineages(),
// captures every transition's NATS payload, renders the entire set as a
// self-contained HTML document and compares it byte-for-byte against
// state_flow_pushed_messages.html on disk. The full HTML (CSS, JS,
// layout, and data) is produced by renderHTML below; the on-disk file
// is purely a generated artifact and must not be hand-edited. Set
// STATE_FLOW_UPDATE=1 to (re)generate it.
func TestStateFlow_Lineages_Payloads(t *testing.T) {
	lineages := allLineages()
	rec := &dumpRecorder{}

	for _, l := range lineages {
		l := l
		t.Run(l.name, func(t *testing.T) {
			runLineage(t, l, rec)
		})
	}

	actualHTML := renderHTML(lineages, rec)
	update := os.Getenv("STATE_FLOW_UPDATE") == "1"

	existing, err := os.ReadFile(lineageHTMLPath)
	switch {
	case err != nil && !os.IsNotExist(err):
		t.Fatalf("read %s: %v", lineageHTMLPath, err)
	case err != nil && !update:
		// File missing in default mode: refuse to silently regenerate
		// (CI must not mask an accidentally-removed golden). Point the
		// developer at the explicit opt-in flag.
		t.Fatalf("%s does not exist. To create it from the current production payload, run:\n"+
			"  STATE_FLOW_UPDATE=1 go test ./controllers/ -run TestStateFlow_Lineages_Payloads -count=1",
			lineageHTMLPath)
	}

	if update {
		if err := os.WriteFile(lineageHTMLPath, []byte(actualHTML), 0o644); err != nil {
			t.Fatalf("write %s: %v", lineageHTMLPath, err)
		}
		if os.IsNotExist(err) {
			t.Logf("created %s (STATE_FLOW_UPDATE=1)", lineageHTMLPath)
		} else {
			t.Logf("regenerated %s (STATE_FLOW_UPDATE=1)", lineageHTMLPath)
		}
		return
	}

	if string(existing) != actualHTML {
		reportHTMLMismatch(t, string(existing), actualHTML, lineages, rec)
	}
}

// reportHTMLMismatch emits a developer-friendly failure report for a
// golden HTML drift. The full actual HTML is written to a tempfile (so
// the developer can open it in a browser to compare visually), and an
// inline unified diff is rendered at the text-payload level — i.e.
// against rec.renderPerLineage's compact text dump — because diffing
// the raw HTML drowns the meaningful (state, op, message, reason)
// changes in CSS/JS noise.
func reportHTMLMismatch(t *testing.T, expectedHTML, actualHTML string,
	lineages []lineage, rec *dumpRecorder) {
	t.Helper()

	actualText := rec.renderPerLineage(lineages)
	expectedText := extractTextDumpFromHTML(expectedHTML)

	udiff := difflib.UnifiedDiff{
		A:        difflib.SplitLines(expectedText),
		B:        difflib.SplitLines(actualText),
		FromFile: lineageHTMLPath + " payload (golden, extracted)",
		ToFile:   "actual payload (this run)",
		Context:  3,
	}
	diffStr, derr := difflib.GetUnifiedDiffString(udiff)
	if derr != nil {
		diffStr = fmt.Sprintf("<failed to render unified diff: %v>", derr)
	}

	maxLines := 400
	if v := os.Getenv("STATE_FLOW_DIFF_LINES"); v != "" {
		if n, err := strconv.Atoi(v); err == nil {
			maxLines = n
		}
	}
	trimmed, trimmedCount := truncateDiff(diffStr, maxLines)

	actualPath := filepath.Join(t.TempDir(), "state_flow_pushed_messages.actual.html")
	if werr := os.WriteFile(actualPath, []byte(actualHTML), 0o644); werr != nil {
		t.Logf("(could not persist actual HTML to %s: %v)", actualPath, werr)
		actualPath = ""
	}

	var hint strings.Builder
	hint.WriteString("state_flow golden HTML drift — production state-machine output changed.\n")
	hint.WriteString("\nIf this change is intentional, regenerate and commit the golden:\n")
	hint.WriteString("  STATE_FLOW_UPDATE=1 go test ./controllers/ -run TestStateFlow_Lineages_Payloads -count=1\n")
	hint.WriteString("\nThe command rewrites the entire ")
	hint.WriteString(lineageHTMLPath)
	hint.WriteString(" file (it is fully generated; do not hand-edit).\n")
	if expectedText == "" {
		hint.WriteString("\n(Could not extract a text payload from the on-disk golden — the\n" +
			"file may be from an older format. Run STATE_FLOW_UPDATE=1 to regenerate.)\n")
	}
	if actualPath != "" {
		hint.WriteString("\nFull actual HTML written to:\n  ")
		hint.WriteString(actualPath)
		hint.WriteString("\n(Open in a browser side-by-side with the on-disk golden for a visual diff.)\n")
	}
	hint.WriteString("\nUnified text-payload diff (golden vs actual)")
	if trimmedCount > 0 {
		fmt.Fprintf(&hint, " — first %d lines (%d more lines truncated; set STATE_FLOW_DIFF_LINES=0 to show all)",
			maxLines, trimmedCount)
	}
	hint.WriteString(":\n")
	hint.WriteString(trimmed)

	t.Error(hint.String())
}

// extractTextDumpFromHTML reconstructs an approximation of the text
// payload (as produced by dumpRecorder.renderPerLineage) by walking
// the markup in expectedHTML and reading the data-* attributes the
// renderer emits on each row. The reconstruction is intentionally
// simple: it relies on the structural invariants of renderHTML, so
// stale or hand-edited HTML may yield "" — in which case the caller
// falls back to a plain "regenerate the golden" hint.
func extractTextDumpFromHTML(html string) string {
	const lineageHeaderToken = `<details class="lineage"`
	if !strings.Contains(html, lineageHeaderToken) {
		return ""
	}
	var sb strings.Builder
	sb.WriteString("==================== LINEAGE-DRIVEN PUSHED MESSAGES ====================\n")
	sb.WriteString("Each lineage starts at <none> and drives the AM through the production\n")
	sb.WriteString("state machine via handler writes + Reconcile ticks. The (state, op,\n")
	sb.WriteString("message, reason) tuple after every step is captured below.\n")
	sb.WriteString("========================================================================\n\n")

	rest := html
	for {
		i := strings.Index(rest, lineageHeaderToken)
		if i < 0 {
			break
		}
		rest = rest[i+len(lineageHeaderToken):]
		name := htmlAttr(rest, "data-name")
		typ := htmlAttr(rest, "data-type")
		wr := htmlAttr(rest, "data-wr") == "true"
		end := strings.Index(rest, "</details>")
		if end < 0 {
			break
		}
		block := rest[:end]
		rest = rest[end+len("</details>"):]

		fmt.Fprintf(&sb, "------ lineage: %s (typ=%s, wr=%t) ------\n", name, typ, wr)
		rowRest := block
		for {
			j := strings.Index(rowRest, "<tr data-step=")
			if j < 0 {
				break
			}
			rowRest = rowRest[j:]
			step := htmlAttr(rowRest, "data-step")
			label := htmlAttr(rowRest, "data-label")
			state := htmlAttr(rowRest, "data-state")
			op := htmlAttr(rowRest, "data-op")
			message := htmlAttr(rowRest, "data-message")
			reason := htmlAttr(rowRest, "data-reason")
			rEnd := strings.Index(rowRest, "</tr>")
			if rEnd < 0 {
				break
			}
			rowRest = rowRest[rEnd+len("</tr>"):]
			fmt.Fprintf(&sb, "  [%s] %-50s -> state=%-22s op=%-10s\n", step, label, state, op)
			fmt.Fprintf(&sb, "        message = %q\n", message)
			fmt.Fprintf(&sb, "        reason  = %q\n", reason)
		}
		sb.WriteString("\n")
	}
	return sb.String()
}

// htmlAttr fishes a single attribute value out of a sub-slice of HTML
// markup. It scans for `name="..."`, returns the (un-escaped) inner
// string, or "" if the attribute is missing. Intended for the narrow
// case in extractTextDumpFromHTML where the markup shape is controlled
// by renderHTML; not a general-purpose HTML parser.
func htmlAttr(s, name string) string {
	needle := name + `="`
	i := strings.Index(s, needle)
	if i < 0 {
		return ""
	}
	rest := s[i+len(needle):]
	j := strings.Index(rest, `"`)
	if j < 0 {
		return ""
	}
	return htmlUnescape(rest[:j])
}

var htmlUnescaper = strings.NewReplacer(
	"&amp;", "&",
	"&lt;", "<",
	"&gt;", ">",
	"&quot;", `"`,
	"&#39;", "'",
)

func htmlUnescape(s string) string { return htmlUnescaper.Replace(s) }

// ---------------------------------------------------------------------------
// HTML rendering
// ---------------------------------------------------------------------------

var htmlEscaper = strings.NewReplacer(
	"&", "&amp;",
	"<", "&lt;",
	">", "&gt;",
	`"`, "&quot;",
	"'", "&#39;",
)

func htmlEscape(s string) string { return htmlEscaper.Replace(s) }

// stateCategory maps an ApplicationManagerState string to a CSS class
// suffix used to colour the corresponding pill. The categories mirror
// the high-level lifecycle phases visible to a user (downloading /
// installing / running / canceling / canceled / failed / …) rather
// than the raw state name, so adding a new state usually does not
// require a new colour.
func stateCategory(state string) string {
	switch {
	case state == "" || state == "<none>":
		return "none"
	case strings.HasSuffix(state, "Canceling"):
		return "canceling"
	case strings.HasSuffix(state, "Canceled"):
		return "canceled"
	case strings.HasSuffix(state, "Failed"), state == "failed":
		return "failed"
	case strings.HasPrefix(state, "upgrad"):
		return "upgrading"
	case strings.HasPrefix(state, "uninstall"):
		return "uninstalling"
	case strings.HasPrefix(state, "stopp") || state == "stopped":
		return "stopping"
	case state == "pending":
		return "pending"
	case state == "downloading":
		return "downloading"
	case state == "installing":
		return "installing"
	case state == "initializing":
		return "initializing"
	case state == "resuming":
		return "resuming"
	case state == "running":
		return "running"
	case state == "suspended" || strings.HasPrefix(state, "suspend"):
		return "suspending"
	case strings.Contains(state, "applyingEnv") || strings.Contains(state, "ApplyingEnv"):
		return "applyingenv"
	}
	return "default"
}

// opCategory maps an OpType string to a CSS class suffix. Operations
// that take a lifecycle (install / upgrade / cancel) get distinct
// colours, while the rarer ops fall back to a neutral pill.
func opCategory(op string) string {
	switch op {
	case "":
		return "none"
	case "install":
		return "install"
	case "cancel":
		return "cancel"
	case "upgrade":
		return "upgrade"
	case "uninstall":
		return "uninstall"
	case "stop", "suspend":
		return "stop"
	case "resume":
		return "resume"
	case "apply_env", "applyEnv":
		return "applyenv"
	}
	return "default"
}

// prettyTransition turns a raw step label (e.g. "pending->downloading"
// or "installing->stopping-podPending") into a visually friendlier
// form ("pending → downloading", "installing → stopping-podPending").
// Only the first "->" is rewritten so any variant suffix is preserved
// as-is — the suffix carries information that the filter input can
// match on (e.g. "podPending").
func prettyTransition(label string) string {
	return strings.Replace(label, "->", " → ", 1)
}

func pluralS(n int) string {
	if n == 1 {
		return ""
	}
	return "s"
}

// renderHTML produces the full state_flow_pushed_messages.html
// document from the captured lineage data. Output is line-oriented:
// one <tr> per recorded transition, one <details> per lineage, with
// stable attribute ordering. Diffs against the on-disk golden are
// therefore row-readable without parsing the markup back.
func renderHTML(lineages []lineage, rec *dumpRecorder) string {
	rowsByLineage := map[string][]dumpRow{}
	for _, r := range rec.rows {
		rowsByLineage[r.lineage] = append(rowsByLineage[r.lineage], r)
	}

	nLineages, nSteps := 0, 0
	for _, l := range lineages {
		rs := rowsByLineage[l.name]
		if len(rs) == 0 {
			continue
		}
		nLineages++
		nSteps += len(rs)
	}

	var sb strings.Builder
	sb.WriteString(htmlHeadTmpl)
	fmt.Fprintf(&sb, "  <span class=\"stats\" id=\"stats\">%d lineage%s · %d step%s</span>\n",
		nLineages, pluralS(nLineages), nSteps, pluralS(nSteps))
	sb.WriteString(htmlHeadCloseTmpl)

	for _, l := range lineages {
		rs := rowsByLineage[l.name]
		if len(rs) == 0 {
			continue
		}
		typStr := string(l.typ)
		fmt.Fprintf(&sb, "<details class=\"lineage\" open data-name=\"%s\" data-type=\"%s\" data-wr=\"%t\">\n",
			htmlEscape(l.name), htmlEscape(typStr), l.wr)
		sb.WriteString("  <summary>\n")
		fmt.Fprintf(&sb, "    <span class=\"lineage-name\">%s</span>\n", htmlEscape(l.name))
		if typStr != "" {
			fmt.Fprintf(&sb, "    <span class=\"pill pill-type\">%s</span>\n", htmlEscape(typStr))
		}
		fmt.Fprintf(&sb, "    <span class=\"step-count\">%d step%s</span>\n", len(rs), pluralS(len(rs)))
		sb.WriteString("  </summary>\n")
		sb.WriteString("  <div class=\"table-wrap\">\n")
		sb.WriteString("  <table>\n")
		sb.WriteString("    <thead><tr>" +
			"<th class=\"col-num\">#</th>" +
			"<th class=\"col-transition\">Transition</th>" +
			"<th class=\"col-state\">State</th>" +
			"<th class=\"col-op\">Op</th>" +
			"<th class=\"col-msg\">Message</th>" +
			"<th class=\"col-reason\">Reason</th></tr></thead>\n")
		sb.WriteString("    <tbody>\n")
		for _, r := range rs {
			stateStr := string(r.state)
			opStr := string(r.op)
			fmt.Fprintf(&sb,
				"      <tr data-step=\"%d\" data-label=\"%s\" data-transition=\"%s\""+
					" data-state=\"%s\" data-op=\"%s\""+
					" data-message=\"%s\" data-reason=\"%s\">"+
					"<td class=\"col-num\">%d</td>"+
					"<td class=\"col-transition\"><code>%s</code></td>"+
					"<td class=\"col-state\"><span class=\"pill pill-state state-%s\">%s</span></td>"+
					"<td class=\"col-op\"><span class=\"pill pill-op op-%s\">%s</span></td>"+
					"<td class=\"col-msg\">%s</td>"+
					"<td class=\"col-reason\"><code>%s</code></td>"+
					"</tr>\n",
				r.step,
				htmlEscape(r.label),
				htmlEscape(prettyTransition(r.label)),
				htmlEscape(stateStr),
				htmlEscape(opStr),
				htmlEscape(r.message),
				htmlEscape(r.reason),
				r.step,
				htmlEscape(prettyTransition(r.label)),
				stateCategory(stateStr), htmlEscape(stateStr),
				opCategory(opStr), htmlEscape(opStr),
				htmlEscape(r.message),
				htmlEscape(r.reason),
			)
		}
		sb.WriteString("    </tbody>\n")
		sb.WriteString("  </table>\n")
		sb.WriteString("  </div>\n")
		sb.WriteString("</details>\n")
	}

	sb.WriteString(htmlTailTmpl)
	return sb.String()
}

// htmlHeadTmpl is the static prelude of the rendered document up to
// (but not including) the stats span — the renderer fills the stats
// in inline so the surrounding header markup never moves between
// runs.
//
// htmlHeadCloseTmpl is the bit immediately after the stats span, up
// to and including the <main> wrapper. Splitting the head in two
// keeps the renderer flat (no template engine needed) while ensuring
// stable byte output.
//
// htmlTailTmpl closes the main element, embeds the filter / expand /
// collapse JS and closes the document.
const (
	htmlHeadTmpl = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>State Flow Pushed Messages</title>
<style>
:root {
  --bg: #0d1117;
  --surface: #161b22;
  --surface-2: #1c2230;
  --border: #30363d;
  --text: #e6edf3;
  --text-muted: #8b949e;
  --accent: #58a6ff;
  --row-hover: rgba(110,118,129,0.10);
  --code-bg: rgba(110,118,129,0.18);
  --hl: #6e5d20;
  --hl-fg: #ffeebb;
  --pill-default-bg: #30363d;
  --pill-default-fg: #c9d1d9;
  --pill-type-bg: rgba(187,128,255,0.18);
  --pill-type-fg: #d2a8ff;
}
* { box-sizing: border-box; }
html, body { margin: 0; padding: 0; }
body {
  background: var(--bg);
  color: var(--text);
  font: 14px/1.5 -apple-system, BlinkMacSystemFont, "Segoe UI", system-ui, sans-serif;
}
.page-header {
  position: sticky; top: 0; z-index: 10;
  padding: 1rem 1.75rem;
  background: linear-gradient(180deg, rgba(13,17,23,0.97) 80%, rgba(13,17,23,0.85));
  backdrop-filter: blur(4px);
  border-bottom: 1px solid var(--border);
}
.page-header h1 { margin: 0; font-size: 1.05rem; font-weight: 600; letter-spacing: 0.01em; }
.page-header .subtitle { margin: 0.2rem 0 0.85rem; color: var(--text-muted); font-size: 0.86rem; }
.controls { display: flex; gap: 0.6rem; align-items: center; flex-wrap: wrap; }
.controls input {
  flex: 1; min-width: 16rem;
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: 6px;
  padding: 0.45rem 0.7rem;
  color: var(--text);
  font: inherit;
}
.controls input:focus { outline: none; border-color: var(--accent); box-shadow: 0 0 0 3px rgba(88,166,255,0.18); }
.controls button {
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: 6px;
  padding: 0.45rem 0.9rem;
  color: var(--text);
  font: inherit;
  cursor: pointer;
  white-space: nowrap;
}
.controls button:hover { background: var(--surface-2); border-color: #444c56; }
.controls .stats {
  color: var(--text-muted);
  font-size: 0.82rem;
  white-space: nowrap;
  margin-left: auto;
  padding-left: 0.5rem;
}

main { padding: 1rem 1.75rem 3rem; max-width: 100%; }

.lineage {
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: 8px;
  margin-bottom: 0.85rem;
  overflow: hidden;
}
.lineage > summary {
  list-style: none;
  cursor: pointer;
  padding: 0.65rem 0.95rem;
  display: flex;
  align-items: center;
  gap: 0.6rem;
  user-select: none;
}
.lineage > summary::-webkit-details-marker { display: none; }
.lineage > summary::before {
  content: "▸";
  color: var(--text-muted);
  font-size: 0.7rem;
  width: 0.8rem;
  display: inline-block;
  transition: transform 0.12s ease-out;
}
.lineage[open] > summary::before { content: "▾"; }
.lineage-name {
  font: 13px/1 ui-monospace, "SF Mono", Menlo, Consolas, monospace;
  font-weight: 600;
}
.step-count { margin-left: auto; color: var(--text-muted); font-size: 0.82rem; }

.table-wrap { overflow-x: auto; }
table {
  width: 100%;
  border-collapse: collapse;
  border-top: 1px solid var(--border);
  table-layout: auto;
}
thead th {
  text-align: left;
  font-size: 0.68rem;
  font-weight: 600;
  color: var(--text-muted);
  text-transform: uppercase;
  letter-spacing: 0.06em;
  padding: 0.5rem 0.95rem;
  border-bottom: 1px solid var(--border);
  background: var(--surface-2);
}
tbody tr { transition: background 0.08s; }
tbody tr:hover { background: var(--row-hover); }
tbody td {
  padding: 0.5rem 0.95rem;
  border-bottom: 1px solid var(--border);
  font-size: 0.875rem;
  vertical-align: top;
}
tbody tr:last-child td { border-bottom: none; }
td.col-num { color: var(--text-muted); width: 2.5rem; font-variant-numeric: tabular-nums; }
td.col-transition code, td.col-reason code {
  font: 12.5px/1.4 ui-monospace, "SF Mono", Menlo, Consolas, monospace;
  background: var(--code-bg);
  padding: 0.1em 0.4em;
  border-radius: 4px;
  color: var(--text);
}
td.col-reason code { color: var(--text-muted); }
td.col-msg { color: var(--text); max-width: 36rem; word-break: break-word; }

.pill {
  display: inline-block;
  padding: 0.18em 0.7em;
  border-radius: 999px;
  font: 12px/1.4 ui-monospace, "SF Mono", Menlo, Consolas, monospace;
  font-weight: 500;
  background: var(--pill-default-bg);
  color: var(--pill-default-fg);
  white-space: nowrap;
}
.pill-type { background: var(--pill-type-bg); color: var(--pill-type-fg); }

/* State pills (background = soft tint, fg = strong) */
.state-none         { background: rgba(110,118,129,0.18); color: #8b949e; }
.state-pending      { background: rgba(56,139,253,0.18); color: #79c0ff; }
.state-downloading  { background: rgba(56,139,253,0.22); color: #79c0ff; }
.state-installing   { background: rgba(35,134,127,0.25); color: #6edcd0; }
.state-initializing { background: rgba(35,134,127,0.20); color: #5eead4; }
.state-resuming     { background: rgba(35,134,127,0.20); color: #5eead4; }
.state-running      { background: rgba(63,185,80,0.18); color: #7ee787; }
.state-stopping     { background: rgba(56,139,253,0.12); color: #58a6ff; }
.state-suspending   { background: rgba(187,128,255,0.16); color: #d2a8ff; }
.state-applyingenv  { background: rgba(35,134,127,0.20); color: #5eead4; }
.state-upgrading    { background: rgba(187,128,255,0.18); color: #d2a8ff; }
.state-uninstalling { background: rgba(248,81,73,0.18); color: #ff7b72; }
.state-canceling    { background: rgba(210,153,34,0.20); color: #e3b341; }
.state-canceled     { background: rgba(248,81,73,0.18); color: #ff8c87; }
.state-failed       { background: rgba(248,81,73,0.22); color: #ff7b72; }
.state-default      { background: var(--pill-default-bg); color: var(--pill-default-fg); }

/* Op pills */
.op-none      { background: rgba(110,118,129,0.18); color: #8b949e; }
.op-install   { background: rgba(56,139,253,0.18); color: #79c0ff; }
.op-cancel    { background: rgba(248,81,73,0.18); color: #ff7b72; }
.op-upgrade   { background: rgba(187,128,255,0.18); color: #d2a8ff; }
.op-uninstall { background: rgba(248,81,73,0.22); color: #ff7b72; }
.op-stop      { background: rgba(210,153,34,0.20); color: #e3b341; }
.op-resume    { background: rgba(63,185,80,0.18); color: #7ee787; }
.op-applyenv  { background: rgba(35,134,127,0.20); color: #5eead4; }
.op-default   { background: var(--pill-default-bg); color: var(--pill-default-fg); }

.hidden { display: none !important; }
mark { background: var(--hl); color: var(--hl-fg); padding: 0 0.1em; border-radius: 2px; }
</style>
</head>
<body>
<header class="page-header">
  <h1>State Flow Pushed Messages</h1>
  <p class="subtitle">Golden snapshot of every (state, op, message, reason) tuple produced by TestStateFlow_Lineages_Payloads.</p>
  <div class="controls">
    <input id="q" type="search" placeholder="Filter: name / state / op / message / reason..." autofocus>
    <button id="expand-all" type="button">Expand all</button>
    <button id="collapse-all" type="button">Collapse all</button>
`
	htmlHeadCloseTmpl = `  </div>
</header>
<main id="root">
`
	htmlTailTmpl = `</main>
<script>
(function () {
  var root = document.getElementById('root');
  var q = document.getElementById('q');
  var stats = document.getElementById('stats');
  var expandBtn = document.getElementById('expand-all');
  var collapseBtn = document.getElementById('collapse-all');

  var lineages = Array.prototype.slice.call(root.querySelectorAll('.lineage'));
  var totalLineages = lineages.length;
  var totalSteps = 0;
  lineages.forEach(function (l) {
    totalSteps += l.querySelectorAll('tbody tr').length;
  });

  function setStats(nL, nS) {
    var lWord = nL === 1 ? 'lineage' : 'lineages';
    var sWord = nS === 1 ? 'step' : 'steps';
    stats.textContent = nL + ' ' + lWord + ' \u00B7 ' + nS + ' ' + sWord;
  }

  function clearMarks(el) {
    el.querySelectorAll('mark').forEach(function (m) {
      var parent = m.parentNode;
      while (m.firstChild) parent.insertBefore(m.firstChild, m);
      parent.removeChild(m);
      parent.normalize();
    });
  }

  function escapeRE(s) { return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'); }

  function highlightCell(td, re) {
    var walker = document.createTreeWalker(td, NodeFilter.SHOW_TEXT, null, false);
    var nodes = [];
    var n;
    while ((n = walker.nextNode())) nodes.push(n);
    nodes.forEach(function (textNode) {
      var text = textNode.nodeValue;
      if (!re.test(text)) return;
      re.lastIndex = 0;
      var frag = document.createDocumentFragment();
      var last = 0;
      var m;
      while ((m = re.exec(text)) !== null) {
        if (m.index > last) frag.appendChild(document.createTextNode(text.slice(last, m.index)));
        var mark = document.createElement('mark');
        mark.textContent = m[0];
        frag.appendChild(mark);
        last = m.index + m[0].length;
        if (m[0].length === 0) re.lastIndex++;
      }
      if (last < text.length) frag.appendChild(document.createTextNode(text.slice(last)));
      textNode.parentNode.replaceChild(frag, textNode);
    });
  }

  function apply(query) {
    var trimmed = (query || '').trim().toLowerCase();
    var re = null;
    if (trimmed) {
      try { re = new RegExp(escapeRE(trimmed), 'gi'); } catch (e) { re = null; }
    }
    var visL = 0, visS = 0;
    lineages.forEach(function (l) {
      clearMarks(l);
      var rows = Array.prototype.slice.call(l.querySelectorAll('tbody tr'));
      var lineageName = (l.getAttribute('data-name') || '').toLowerCase();
      var lineageType = (l.getAttribute('data-type') || '').toLowerCase();
      var nameMatch = trimmed && (lineageName.indexOf(trimmed) !== -1 || lineageType.indexOf(trimmed) !== -1);
      var anyRow = false;
      rows.forEach(function (r) {
        if (!trimmed) {
          r.classList.remove('hidden');
          anyRow = true;
          return;
        }
        var blob = [
          r.getAttribute('data-label') || '',
          r.getAttribute('data-state') || '',
          r.getAttribute('data-op') || '',
          r.getAttribute('data-message') || '',
          r.getAttribute('data-reason') || ''
        ].join(' ').toLowerCase();
        var match = nameMatch || blob.indexOf(trimmed) !== -1;
        r.classList.toggle('hidden', !match);
        if (match) anyRow = true;
      });
      l.classList.toggle('hidden', !anyRow && !nameMatch);
      if (!l.classList.contains('hidden')) {
        visL++;
        visS += l.querySelectorAll('tbody tr:not(.hidden)').length;
        if (re) {
          l.querySelectorAll('.lineage-name').forEach(function (cell) { highlightCell(cell, re); });
          l.querySelectorAll('tbody tr:not(.hidden) td').forEach(function (cell) { highlightCell(cell, re); });
        }
      }
    });
    setStats(visL, visS);
  }

  q.addEventListener('input', function () { apply(q.value); });
  expandBtn.addEventListener('click', function () {
    lineages.forEach(function (l) { l.open = true; });
  });
  collapseBtn.addEventListener('click', function () {
    lineages.forEach(function (l) { l.open = false; });
  });

  setStats(totalLineages, totalSteps);
})();
</script>
</body>
</html>
`
)

// truncateDiff caps `s` at maxLines lines. If maxLines <= 0 it returns
// the input unchanged. Returns the (possibly trimmed) text and the
// number of lines that were dropped.
func truncateDiff(s string, maxLines int) (string, int) {
	if maxLines <= 0 {
		return s, 0
	}
	lines := strings.SplitAfter(s, "\n")
	if len(lines) <= maxLines {
		return s, 0
	}
	return strings.Join(lines[:maxLines], ""), len(lines) - maxLines
}

// edgesBlockedOnSeams enumerates reconcile-driven edges that exist in
// production and are listed in appstate.ReconcileDrivenTransitions but
// cannot yet be lineage-driven end-to-end. Each entry must reference an
// open seam-refactor justification: removing one without addressing the
// referenced seam will cause this allow-list to drift from reality.
//
// The list is the single source of truth for "edge is intentionally
// uncovered". TestStateFlow_Lineages_CoversReconcileEdges treats every
// other edge as a hard failure if a lineage step is missing.
var edgesBlockedOnSeams = map[string]string{
	// UpgradingApp.Exec calls real cluster paths (helm.InitConfig,
	// kubesphere.GetAdminUsername, apputils.GetAppConfig /
	// apputils.GetIndexAndDownloadChart) before the happy-path
	// transitions fire. Only IsAdmin is seamed today; the others must
	// land before these three edges can be driven against fakes.
	"upgrading->initializing":  "blocked on UpgradingApp seam refactor (helm.InitConfig + GetAdminUsername + GetAppConfig)",
	"upgrading->stopped":       "blocked on UpgradingApp seam refactor (same dependency chain as upgrading->initializing)",
	"upgrading->upgradeFailed": "blocked on UpgradingApp seam refactor; helm.upgradeErr is unreachable while pre-helm cluster calls fail first",
}

// TestStateFlow_Lineages_CoversReconcileEdges pins every edge declared in
// pkg/appstate.ReconcileDrivenTransitions to at least one lineage step,
// so a new reconcile-driven transition added to production cannot be
// landed without a corresponding lineage update. Edges that are known to
// be inexpressible against today's seams are allow-listed in
// edgesBlockedOnSeams with a documented justification.
func TestStateFlow_Lineages_CoversReconcileEdges(t *testing.T) {
	covered := map[string]bool{}
	for _, l := range allLineages() {
		for i, s := range l.steps {
			if s.kind != driverReconcile {
				continue
			}
			if i == 0 {
				continue
			}
			from := l.steps[i-1].wantState
			to := s.wantState
			if from == "" || to == "" {
				continue
			}
			covered[from.String()+"->"+to.String()] = true
		}
	}

	for _, edge := range appstate.ReconcileDrivenTransitions {
		key := edge[0].String() + "->" + edge[1].String()
		if !covered[key] {
			if reason, blocked := edgesBlockedOnSeams[key]; blocked {
				t.Logf("edge %s uncovered (allow-listed): %s", key, reason)
				continue
			}
			t.Errorf("ReconcileDrivenTransitions edge %s has no lineage step "+
				"(add a lineage step or, if intentionally inexpressible, an entry "+
				"in edgesBlockedOnSeams)", key)
		}
		if !appstate.IsStateTransitionValid(edge[0], edge[1]) {
			t.Errorf("ReconcileDrivenTransitions edge %s is not in StateTransitions", key)
		}
	}

	// Reverse check: every allow-listed edge must still exist in
	// ReconcileDrivenTransitions, so the list does not silently outlive
	// the seam refactor it's tracking.
	declared := map[string]bool{}
	for _, e := range appstate.ReconcileDrivenTransitions {
		declared[e[0].String()+"->"+e[1].String()] = true
	}
	for k := range edgesBlockedOnSeams {
		if !declared[k] {
			t.Errorf("edgesBlockedOnSeams[%s] is no longer in ReconcileDrivenTransitions — drop the entry", k)
		}
	}
}
