package files

import (
	"context"
	"errors"
	"fmt"
	"io"

	"github.com/spf13/cobra"

	"github.com/beclab/Olares/cli/internal/files/share"
	"github.com/beclab/Olares/cli/pkg/cmdutil"
)

// This file implements the three share-record update verbs that
// mirror the LarePass app's Reset-Password / Edit-Permissions /
// Edit-SMB-Members modal flows:
//
//	share set-password <share-id> [--password STR]   → PUT /api/share/share_password/
//	share set-members  <share-id> --users a:view,b:edit | --clear
//	                                                  → PUT /api/share/share_path/share_members/
//	share set-smb      <share-id> --public | --users smb-id:perm,... [--read-only]
//	                                                  → POST /api/share/smb_share_member/
//
// Design choices that recur across the three verbs:
//
//   - Every verb runs a Query first to fetch the share record, then
//     hands it to requireShareType. A `set-password` against an
//     internal share, etc., is rejected client-side with a message
//     pointing at the right verb, instead of letting the server emit
//     an opaque 4xx that gives the user no recovery path.
//
//   - The mutation calls (UpdateInternalMembers / UpdateSMBShareMember
//     / ResetPassword) are already implemented in the share package —
//     this file is just the cobra-side glue. Keeping the wire shape
//     unchanged means a CLI update is wire-compatible with the
//     LarePass app's modal flows.
//
//   - --users on set-members reuses parseShareMembers from share_create.go;
//     --users on set-smb reuses parseSMBUsers (which also enforces the
//     view/edit-only rule the SMB endpoint requires). Single source
//     of truth for the parsing keeps create and update in lock-step.

// shareSetPasswordOptions captures the flags exclusive to
// `share set-password`. Mirrors the password handling of
// `share public` (auto-gen on omission, ≥6 chars on input) so the
// rules are identical between create and reset; users don't have to
// remember a separate ruleset for the update verb.
type shareSetPasswordOptions struct {
	password string
}

// newShareSetPasswordCommand: `share set-password <share-id> [--password STR]`.
//
// Reset (or set) the access password for a Public-link share. Mirrors
// the LarePass app's Reset-Password modal at
// apps/.../components/files/share/ShareResetPassword.vue, which calls
// share.resetPassword(path_id, password).
func newShareSetPasswordCommand(f *cmdutil.Factory) *cobra.Command {
	o := &shareSetPasswordOptions{}
	cmd := &cobra.Command{
		Use:   "set-password <share-id>",
		Short: "reset the access password of a Public-link share",
		Long: `Reset (or set) the access password for an existing Public-link share.

Wire shape:

    PUT /api/share/share_password/
        body: {path_id: "<share-id>", password: "<new-password>"}

The share id stays stable across a password reset — recipients keep
the same /sharable-link/<id>/ URL but need the new password the
next time they open it.

--password is optional: when omitted, the CLI generates an 8-byte
URL-safe random password (crypto/rand → base64.RawURLEncoding,
≈11 chars) and prints it ONCE. The server does not echo passwords
back on subsequent share reads (` + "`share get`" + ` / ` + "`share list`" + ` show
the share record but not the cleartext password), so capture the
output the first time.

Minimum password length is 6 characters (matches the LarePass app's
passwordLimitRule and the Public-link create-time validation).

Only Public-link shares accept this verb. Internal and SMB shares
don't carry a recipient password (Internal uses Olares user identity;
SMB issues per-share smb_user / smb_password) — running set-password
against those is rejected client-side with a pointer to the right
verb.

Examples:

    # Auto-generated random password.
    olares-cli files share set-password <share-id>

    # Explicit password.
    olares-cli files share set-password <share-id> --password "n3w-pw-1"
`,
		Args: cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			return runShareSetPassword(cmd.Context(), f, cmd.OutOrStdout(), args[0], o)
		},
	}
	cmd.Flags().StringVar(&o.password, "password", "",
		"new access password; if omitted, an 8-byte random password is generated and printed")
	return cmd
}

func runShareSetPassword(
	ctx context.Context,
	f *cmdutil.Factory,
	out io.Writer,
	shareID string,
	o *shareSetPasswordOptions,
) error {
	if ctx == nil {
		ctx = context.Background()
	}
	if shareID == "" {
		return errors.New("share id is required")
	}

	password := o.password
	autoGenerated := false
	if password == "" {
		var err error
		password, err = generatePassword(8)
		if err != nil {
			return fmt.Errorf("generate random password: %w", err)
		}
		autoGenerated = true
	}
	// Same lower bound as `share public` — keeps the create-vs-reset
	// validation aligned so users don't get a "valid at create-time
	// but rejected at reset-time" surprise.
	if len(password) < 6 {
		return errors.New("--password must be at least 6 characters")
	}

	client, rp, err := setupShareClient(ctx, f)
	if err != nil {
		return err
	}

	// Pre-flight Query so we can reject a non-Public share BEFORE
	// hitting the password endpoint. The server might also reject
	// (the password column has no meaning for SMB / Internal), but
	// surfacing the type mismatch up front gives the user a clear
	// recovery path instead of a generic 4xx.
	rec, err := client.Query(ctx, shareID)
	if err != nil {
		return reformatShareHTTPErr(err, rp.OlaresID, "look up share "+shareID)
	}
	if err := requireShareType(rec, share.TypePublic, "set the password of", shareID); err != nil {
		return err
	}

	if err := client.ResetPassword(ctx, shareID, password); err != nil {
		return reformatShareHTTPErr(err, rp.OlaresID, "reset password for share "+shareID)
	}

	fmt.Fprintf(out, "updated public share password:\n")
	fmt.Fprintf(out, "  id        : %s\n", rec.ID)
	fmt.Fprintf(out, "  path      : %s\n", resolveShareDisplayPath(ctx, f, rec))
	fmt.Fprintf(out, "  password  : %s", password)
	if autoGenerated {
		fmt.Fprintf(out, "  (auto-generated; copy now, the server doesn't echo it back on subsequent reads)")
	}
	fmt.Fprintln(out)
	return nil
}

// shareSetMembersOptions captures the flags exclusive to
// `share set-members`. The two are mutually exclusive: --users
// REPLACES the member list with the parsed entries, --clear empties
// it explicitly. Forcing the user to choose one (rather than
// inferring "empty users means clear") guards against the foot-gun
// where a typo'd or empty --users silently wipes every member.
type shareSetMembersOptions struct {
	usersRaw string
	clear    bool
}

// newShareSetMembersCommand: `share set-members <share-id>
// (--users name:perm,... | --clear)`.
//
// Mirrors the LarePass app's "Edit Permissions" modal for Internal
// shares (apps/.../components/files/share/Internal/internal.ts L137-147,
// which calls share.updateInternalShareMembers when shareId already
// exists). Wire-compatible — the server treats web-app updates and
// CLI updates identically.
func newShareSetMembersCommand(f *cmdutil.Factory) *cobra.Command {
	o := &shareSetMembersOptions{}
	cmd := &cobra.Command{
		Use:   "set-members <share-id>",
		Short: "replace the member list of an Internal share (REPLACES, not append)",
		Long: `Replace the entire member list of an Internal share with --users
(or empty it with --clear). REPLACES, not appends — every existing
member not listed in --users is dropped.

Wire shape:

    PUT /api/share/share_path/share_members/
        body: {path_id: "<share-id>",
               share_members: [{share_member: "<name>", permission: <int>}, ...]}

Only Internal shares accept this verb. Public links don't have a
member list (recipients identify themselves via the link password);
SMB shares use a different account model (SMB-account IDs, not
Olares user names) and have their own update verb.

--users format mirrors ` + "`share internal --users`" + `:

    name1:perm1,name2:perm2,name3   (perm defaults to "view" if omitted)

Permissions: view / upload / edit / admin (or 1..4). Empty
permission falls back to "view".

--users and --clear are mutually exclusive. Pass --clear to drop
every member without re-listing them; the share record stays but
becomes private to its owner until the next set-members.

Adding to (not replacing) an existing member list is NOT supported
on the wire — the LarePass app uses a "create + add-member" sequence
for additive flows, exposed via ` + "`share internal`" + ` (which uses
add-member after create). For an additive update, list every
existing member plus the new one in --users.

Examples:

    # Replace the member list with two users.
    olares-cli files share set-members <share-id> \
        --users alice:edit,bob:view

    # Promote bob from view to admin (carry alice through unchanged).
    olares-cli files share set-members <share-id> \
        --users alice:edit,bob:admin

    # Make the share private to its owner — drop every member.
    olares-cli files share set-members <share-id> --clear
`,
		Args: cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			return runShareSetMembers(cmd.Context(), f, cmd.OutOrStdout(), args[0], o)
		},
	}
	cmd.Flags().StringVar(&o.usersRaw, "users", "",
		"replacement member list: name[:perm],name[:perm]... (perm: view/upload/edit/admin, default view)")
	cmd.Flags().BoolVar(&o.clear, "clear", false,
		"drop every member (mutually exclusive with --users)")
	return cmd
}

func runShareSetMembers(
	ctx context.Context,
	f *cmdutil.Factory,
	out io.Writer,
	shareID string,
	o *shareSetMembersOptions,
) error {
	if ctx == nil {
		ctx = context.Background()
	}
	if shareID == "" {
		return errors.New("share id is required")
	}
	if o.clear && o.usersRaw != "" {
		return errors.New("--users and --clear are mutually exclusive (pass exactly one)")
	}
	if !o.clear && o.usersRaw == "" {
		// Refusing the no-flag form is deliberate: a silent
		// "empty users == clear" rule would let a typo or a
		// shell-quoting accident wipe every member without any
		// confirmation.
		return errors.New("`share set-members` requires --users <list> OR --clear (the share has to map to an explicit member set)")
	}

	var members []share.Member
	if !o.clear {
		parsed, err := parseShareMembers(o.usersRaw)
		if err != nil {
			return fmt.Errorf("--users: %w", err)
		}
		// parseShareMembers returns nil for an all-whitespace
		// input. Guard explicitly so an accidental --users " ,, "
		// surfaces as "no usable entries" rather than a silent
		// empty PUT.
		if len(parsed) == 0 {
			return errors.New("--users contained no usable entries; use --clear to empty the member list intentionally")
		}
		members = parsed
	}

	client, rp, err := setupShareClient(ctx, f)
	if err != nil {
		return err
	}

	rec, err := client.Query(ctx, shareID)
	if err != nil {
		return reformatShareHTTPErr(err, rp.OlaresID, "look up share "+shareID)
	}
	if err := requireShareType(rec, share.TypeInternal, "set the member list of", shareID); err != nil {
		return err
	}

	// share.UpdateInternalMembers accepts an empty members slice as
	// "clear all" — exactly what we want for --clear. No
	// special-casing needed here.
	if err := client.UpdateInternalMembers(ctx, shareID, members); err != nil {
		return reformatShareHTTPErr(err, rp.OlaresID, "update internal share members for "+shareID)
	}

	fmt.Fprintf(out, "updated internal share members:\n")
	fmt.Fprintf(out, "  id        : %s\n", rec.ID)
	fmt.Fprintf(out, "  path      : %s\n", resolveShareDisplayPath(ctx, f, rec))
	if len(members) == 0 {
		fmt.Fprintln(out, "  members   : (cleared — share is private to its owner until set-members is re-run)")
		return nil
	}
	fmt.Fprintf(out, "  members   :\n")
	for _, m := range members {
		fmt.Fprintf(out, "    - %s  (%s)\n", m.ShareMember, m.Permission)
	}
	return nil
}

// shareSetSMBOptions captures the flags exclusive to
// `share set-smb`. Same shape as shareSMBOptions for `share smb`
// create — keeping the surface identical so muscle memory carries
// over between create and update.
type shareSetSMBOptions struct {
	publicSMB bool
	readOnly  bool
	usersRaw  string
}

// newShareSetSMBCommand: `share set-smb <share-id> (--public |
// --users smb-id:perm,...) [--read-only]`.
//
// Mirrors the LarePass app's SMB edit-mode at
// apps/.../components/files/share/SMB/smb.ts L79-104, which calls
// share.updateSMBShareMember(path_id, users, public_smb).
func newShareSetSMBCommand(f *cmdutil.Factory) *cobra.Command {
	o := &shareSetSMBOptions{}
	cmd := &cobra.Command{
		Use:   "set-smb <share-id>",
		Short: "update the member list / public-mode of an SMB share",
		Long: `Replace the SMB-account list of an existing SMB share, or flip it
to public-SMB mode (any client on the local network can mount).

Wire shape:

    POST /api/share/smb_share_member/
        body: {path_id: "<share-id>",
               users: [{id: "<smb-account-id>", permission: <int>}, ...],
               public_smb: <bool>}

Only SMB shares accept this verb. The endpoint replaces the member
list outright (REPLACES, not appends), and --public flips the share
to "anyone on the local network" mode.

Mutually exclusive recipient model (one MUST be passed):

    --public              public-SMB mode; users array sent empty
    --users id:perm,...   per-user SMB; public_smb sent false

--users entries are SMB-account IDs (NOT Olares user names — list
them with ` + "`share smb-users list`" + `). Permission is one of view / edit
(or 1 / 3); upload / admin are rejected because the SMB endpoint
doesn't grant those.

--read-only forces every entry's permission to view, regardless of
each entry's :perm annotation. Public-SMB mode forces edit at the
share-record level (matches the web app's createSMBShare logic).

Examples:

    # Switch the share to public-SMB.
    olares-cli files share set-smb <share-id> --public

    # Replace the member list with two SMB users.
    olares-cli files share set-smb <share-id> \
        --users smb-uid-1:edit,smb-uid-2:view

    # Demote everyone to read-only.
    olares-cli files share set-smb <share-id> \
        --users smb-uid-1,smb-uid-2 --read-only
`,
		Args: cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			return runShareSetSMB(cmd.Context(), f, cmd.OutOrStdout(), args[0], o)
		},
	}
	cmd.Flags().BoolVar(&o.publicSMB, "public", false,
		"public-SMB mode: anyone on the local network can mount (mutually exclusive with --users)")
	cmd.Flags().BoolVar(&o.readOnly, "read-only", false,
		"force every entry's permission to view (read-only); default per --users is edit")
	cmd.Flags().StringVar(&o.usersRaw, "users", "",
		"replacement SMB-account list: id[:perm],id[:perm]... (perm: view/edit, default edit)")
	return cmd
}

func runShareSetSMB(
	ctx context.Context,
	f *cmdutil.Factory,
	out io.Writer,
	shareID string,
	o *shareSetSMBOptions,
) error {
	if ctx == nil {
		ctx = context.Background()
	}
	if shareID == "" {
		return errors.New("share id is required")
	}
	if o.publicSMB && o.usersRaw != "" {
		return errors.New("--public and --users are mutually exclusive (public-SMB mode does not take a member list)")
	}
	if !o.publicSMB && o.usersRaw == "" {
		return errors.New("`share set-smb` requires either --public OR --users (the share has to be visible to someone)")
	}

	users, err := parseSMBUsers(o.usersRaw, o.readOnly)
	if err != nil {
		return fmt.Errorf("--users: %w", err)
	}
	// parseSMBUsers returns nil for empty/whitespace input. When
	// --public isn't set we already required --users to be non-empty
	// above, but the parser may still return zero entries if every
	// comma-segment was blank — surface that as a usage error.
	if !o.publicSMB && len(users) == 0 {
		return errors.New("--users contained no usable SMB-account entries (need id[:perm],...)")
	}

	client, rp, err := setupShareClient(ctx, f)
	if err != nil {
		return err
	}

	rec, err := client.Query(ctx, shareID)
	if err != nil {
		return reformatShareHTTPErr(err, rp.OlaresID, "look up share "+shareID)
	}
	if err := requireShareType(rec, share.TypeSMB, "update the member list of", shareID); err != nil {
		return err
	}

	// Use a typed nil slice for the public-SMB body so the JSON
	// renders as `users: []`, matching what the web app sends —
	// `users: null` would be wire-different even if the server
	// happens to accept both today.
	body := users
	if o.publicSMB {
		body = []share.SMBUser{}
	}
	if err := client.UpdateSMBShareMember(ctx, shareID, body, o.publicSMB); err != nil {
		return reformatShareHTTPErr(err, rp.OlaresID, "update SMB share members for "+shareID)
	}

	fmt.Fprintf(out, "updated SMB share:\n")
	fmt.Fprintf(out, "  id            : %s\n", rec.ID)
	fmt.Fprintf(out, "  path          : %s\n", resolveShareDisplayPath(ctx, f, rec))
	fmt.Fprintf(out, "  public access : %t\n", o.publicSMB)
	if !o.publicSMB && len(users) > 0 {
		fmt.Fprintf(out, "  members       :\n")
		for _, u := range users {
			fmt.Fprintf(out, "    - %s  (%s)\n", u.ID, u.Permission)
		}
	}
	return nil
}
