# Keep in sync with framework/app-gateway/config/defaults.yaml
namespace: app-gateway

gateway:
  name: app-gateway
  gatewayClassName: olares-app-gateway

demo:
  enabled: true
  host: demo.agw.local
