---
apiVersion: v1
kind: Service
metadata:
  name: files-provider-svc
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: system-provider
  ports:
    - name: server
      protocol: TCP
      port: 28080
      targetPort: 28080

---
# provider role
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backend:files-provider
  annotations:
    provider-registry-ref: {{ .Release.Namespace }}/files-provider-svc
    provider-service-ref: files-provider-svc.{{ .Release.Namespace }}:28080
rules:
  - nonResourceURLs:
      - "/api/resources/*"
      - "/api/paste/*"
      - "/api/raw/*"
      - "/api/md5/*"
      - "/api/permission/*"
      - "/api/preview/*"
      - "/api/repos/*"
      - "/api/nodes/*"
      - "/api/stream/*"
      - "/api/tree/*"
      - "/api/share/*"
      - "/api/users/*"
      - "/api/archive/*"
      - "/upload/*"
      - "/videos/*"
    verbs: ["*"]

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: files-provider-nginx-config
  namespace: {{ .Release.Namespace }}
  annotations:
    kubesphere.io/creator: bytetrade.io
data:
  files.conf: |-
    server {
        listen 8080;
        server_name  files-provider-svc.{{ .Release.Namespace }};
        # Gzip Settings
        gzip on;
        gzip_disable "msie6";
        gzip_min_length 1k;
        gzip_buffers 16 64k;
        gzip_http_version 1.1;
        gzip_comp_level 6;
        gzip_types *;
        index index.html;
        # wise uploads / large file downloads; keep in step with wise.conf.
        client_max_body_size 4000M;
        location / {
          proxy_pass http://files-service.os-framework:80;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection '$connection_upgrade';
        }
    }
