


---
apiVersion: v1
kind: Service
metadata:
  name: citus-master-svc
  namespace: user-system-{{ .Values.bfl.username }}
spec:
  type: ClusterIP
  selector:
    app: systemserver
  ports:
    - protocol: TCP
      name: citus
      port: 5432
      targetPort: 5432

# pg request demo
# ---
# apiVersion: apr.bytetrade.io/v1alpha1
# kind: MiddlewareRequest
# metadata:
#   name: test-pg
#   namespace: user-system-{{ .Values.bfl.username }}
# spec:
#   app: test
#   appNamespace: user-space-{{ .Values.bfl.username }}
#   middleware: postgres
#   postgreSQL:
#     user: testuser
#     password: 
#       value: postgres
#     databases:
#     - name: testdb 
    
