apiVersion: v1
kind: Service
metadata:
  name: knowledge-base-api
  namespace: user-system-{{ .Values.bfl.username }}
spec:
  type: ClusterIP
  selector:
    app: systemserver
  ports:
    - protocol: TCP
      name: knowledge-api
      port: 3010
      targetPort: 3010  
