apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: os-system:argoworkflow-workflow-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argoworkflow-workflow-controller
subjects:
  - kind: ServiceAccount
    name: argoworkflow-workflow-controller
    namespace: os-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: os-system:argoworkflow-workflow-controller-cluster-template
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argoworkflow-workflow-controller-cluster-template
subjects:
  - kind: ServiceAccount
    name: argoworkflow-workflow-controller
    namespace: os-system

