apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argoworkflow-workflow
  labels:
    app.kubernetes.io/component=workflow-controller
    app.kubernetes.io/instance=argo
    app.kubernetes.io/managed-by=Helm
    app.kubernetes.io/name=argoworkflows-workflow-controller
    app.kubernetes.io/part-of=argo-workflows
    helm.sh/chart=argoworkflows-0.35.0
  namespace: os-system
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - watch
      - patch
  - apiGroups:
      - ""
    resources:
      - pods/log
    verbs:
      - get
      - watch
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs:
      - create
  - apiGroups:
      - argoproj.io
    resources:
      - workflowtaskresults
    verbs:
      - create
  - apiGroups:
      - argoproj.io
    resources:
      - workflowtasksets
      - workflowartifactgctasks
    verbs:
      - list
      - watch
  - apiGroups:
      - argoproj.io
    resources:
      - workflowtasksets/status
      - workflowartifactgctasks/status
    verbs:
      - patch

