apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: os-system:argoworkflow-workflow-controller
  labels:
    app.kubernetes.io/component=workflow-controller
    app.kubernetes.io/instance=argo
    app.kubernetes.io/managed-by=Helm
    app.kubernetes.io/name=argoworkflows-workflow-controller
    app.kubernetes.io/part-of=argo-workflows
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argoworkflow-workflow-controller
subjects:
  - kind: ServiceAccount
    name: argoworkflow-workflow-controller
    namespace: os-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: os-system:argoworkflow-workflow-controller-cluster-template
  labels:
    app.kubernetes.io/component=workflow-controller
    app.kubernetes.io/instance=argo
    app.kubernetes.io/managed-by=Helm
    app.kubernetes.io/name=argoworkflows-workflow-controller
    app.kubernetes.io/part-of=argo-workflows
    helm.sh/chart=argoworkflows-0.35.0
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argoworkflow-workflow-controller-cluster-template
subjects:
  - kind: ServiceAccount
    name: argoworkflow-workflow-controller
    namespace: os-system

