package sidecar

import (
	"fmt"
	"strings"
	"testing"

	"github.com/beclab/Olares/framework/app-service/pkg/constants"
)

// TestGenerateIptablesCommands_LinkerdProxyUidExempt asserts that the
// olares-envoy-sidecar iptables rules generated by generateIptablesCommands
// explicitly exempt the Linkerd proxy uid from PROXY_OUTBOUND redirection.
//
// Without this exemption, a pod that is simultaneously injected by Linkerd
// AND by olares-envoy-sidecar will have its `linkerd-proxy` (uid 2102)
// control-plane bootstrap traffic to identity:8080 captured by envoy on
// 15001. envoy then parses the TLS ClientHello as HTTP and replies with
// `HTTP/1.1 400 Bad Request`, which the proxy reports as
// `received corrupt message of type InvalidContentType`, breaking mTLS
// bootstrap and leaving the pod stuck in PodInitializing.
//
// See: archdoc Shared 集群内访问 v1.0.3 §16.
func TestGenerateIptablesCommands_LinkerdProxyUidExempt(t *testing.T) {
	cmd := generateIptablesCommands(nil)

	wantLine := fmt.Sprintf("-A PROXY_OUTBOUND -m owner --uid-owner %d -j RETURN", constants.LinkerdProxyUID)
	if !strings.Contains(cmd, wantLine) {
		t.Fatalf("generateIptablesCommands missing linkerd-proxy uid (%d) exemption.\nWant line:\n  %s\nGot:\n%s",
			constants.LinkerdProxyUID, wantLine, cmd)
	}

	// Both exemptions (envoy uid 1555 + linkerd-proxy uid 2102) must appear
	// BEFORE the redirect catch-all, otherwise the RETURN never matches.
	exemptIdx := strings.Index(cmd, wantLine)
	redirectIdx := strings.Index(cmd, "-A PROXY_OUTBOUND -j PROXY_OUT_REDIRECT")
	if exemptIdx == -1 || redirectIdx == -1 || exemptIdx > redirectIdx {
		t.Fatalf("linkerd-proxy uid RETURN must precede PROXY_OUT_REDIRECT catch-all; "+
			"exemptIdx=%d redirectIdx=%d", exemptIdx, redirectIdx)
	}
}

// TestGenerateIptablesCommands_EnvoyUidExempt is a sanity check to ensure
// the pre-existing envoy self-exemption keeps working alongside the new
// linkerd-proxy uid rule.
func TestGenerateIptablesCommands_EnvoyUidExempt(t *testing.T) {
	cmd := generateIptablesCommands(nil)

	wantLine := fmt.Sprintf("-A PROXY_OUTBOUND -m owner --uid-owner %d -j RETURN", constants.EnvoyUID)
	if !strings.Contains(cmd, wantLine) {
		t.Fatalf("generateIptablesCommands missing envoy uid (%d) exemption.\nWant line:\n  %s\nGot:\n%s",
			constants.EnvoyUID, wantLine, cmd)
	}
}
