package sidecar

import (
	"fmt"
	"strings"
	"testing"

	"github.com/beclab/Olares/framework/app-service/pkg/appcfg"
	"github.com/beclab/Olares/framework/app-service/pkg/constants"
	"github.com/stretchr/testify/require"
)

// TestGenerateIptablesCommands_LinkerdProxyUidExempt asserts that the
// olares-envoy-sidecar iptables rules generated by generateIptablesCommands
// explicitly exempt the Linkerd proxy uid from PROXY_OUTBOUND redirection.
//
// Without this exemption, a pod that is simultaneously injected by Linkerd
// AND by olares-envoy-sidecar will have its `linkerd-proxy` (uid 2102)
// control-plane bootstrap traffic to identity:8080 captured by envoy on
// 15001. envoy then parses the TLS ClientHello as HTTP and replies with
// `HTTP/1.1 400 Bad Request`, which the proxy reports as
// `received corrupt message of type InvalidContentType`, breaking mTLS
// bootstrap and leaving the pod stuck in PodInitializing.
//
// Regression guard for the linkerd-proxy uid iptables exemption.
func TestGenerateIptablesCommands_LinkerdProxyUidExempt(t *testing.T) {
	cmd := generateIptablesCommands(nil, false)

	wantLine := fmt.Sprintf("-A PROXY_OUTBOUND -m owner --uid-owner %d -j RETURN", constants.LinkerdProxyUID)
	if !strings.Contains(cmd, wantLine) {
		t.Fatalf("generateIptablesCommands missing linkerd-proxy uid (%d) exemption.\nWant line:\n  %s\nGot:\n%s",
			constants.LinkerdProxyUID, wantLine, cmd)
	}

	// Both exemptions (envoy uid 1555 + linkerd-proxy uid 2102) must appear
	// BEFORE the redirect catch-all, otherwise the RETURN never matches.
	exemptIdx := strings.Index(cmd, wantLine)
	redirectIdx := strings.Index(cmd, "-A PROXY_OUTBOUND -j PROXY_OUT_REDIRECT")
	if exemptIdx == -1 || redirectIdx == -1 || exemptIdx > redirectIdx {
		t.Fatalf("linkerd-proxy uid RETURN must precede PROXY_OUT_REDIRECT catch-all; "+
			"exemptIdx=%d redirectIdx=%d", exemptIdx, redirectIdx)
	}
}

// TestGenerateIptablesCommands_EnvoyUidExempt is a sanity check to ensure
// the pre-existing envoy self-exemption keeps working alongside the new
// linkerd-proxy uid rule.
func TestInboundBypassPorts_includesEntrancePorts(t *testing.T) {
	cfg := &appcfg.ApplicationConfig{
		Entrances: []appcfg.Entrance{
			{Name: "terminal", Port: 8081},
			{Name: "api", Port: 8080},
		},
	}
	got := inboundBypassPorts(cfg)
	require.ElementsMatch(t, []int{8081, 8080}, got)

	cmd := generateIptablesCommands(cfg, false)
	require.Contains(t, cmd, "-A PROXY_INBOUND -p tcp --dport 8081 -j RETURN")
	require.Contains(t, cmd, "-A PROXY_INBOUND -p tcp --dport 8080 -j RETURN")
}

func TestGenerateIptablesCommands_EnvoyUidExempt(t *testing.T) {
	cmd := generateIptablesCommands(nil, false)

	wantLine := fmt.Sprintf("-A PROXY_OUTBOUND -m owner --uid-owner %d -j RETURN", constants.EnvoyUID)
	if !strings.Contains(cmd, wantLine) {
		t.Fatalf("generateIptablesCommands missing envoy uid (%d) exemption.\nWant line:\n  %s\nGot:\n%s",
			constants.EnvoyUID, wantLine, cmd)
	}
}

// TestGenerateIptablesCommands_ServicePortsBypass locks main's pre-merge
// PROXY_INBOUND RETURN rules for ApplicationConfig.Ports (tcp only).
func TestGenerateIptablesCommands_ServicePortsBypass(t *testing.T) {
	cfg := &appcfg.ApplicationConfig{
		Ports: []appcfg.ServicePort{
			{Port: 9000, Protocol: "tcp"},
			{Port: 53, Protocol: "udp"},
			{Port: 9001, Protocol: ""},
		},
	}
	cmd := generateIptablesCommands(cfg, false)
	require.Contains(t, cmd, "-A PROXY_INBOUND -p tcp --dport 9000 -j RETURN")
	require.Contains(t, cmd, "-A PROXY_INBOUND -p tcp --dport 9001 -j RETURN")
	require.NotContains(t, cmd, "--dport 53 ")
}

// TestGenerateIptablesCommands_MacvlanBypass locks overlay-gateway macvlan
// bypass rules from main (#3239): net1 traffic must not hit envoy redirect.
func TestGenerateIptablesCommands_MacvlanBypass(t *testing.T) {
	cmd := generateIptablesCommands(nil, true)
	require.Contains(t, cmd, "-A PROXY_INBOUND -i ${MACVLAN_IFACE} -j RETURN")
	require.Contains(t, cmd, "-A PROXY_OUTBOUND -o ${MACVLAN_IFACE} -j RETURN")

	inboundIdx := strings.Index(cmd, "-A PROXY_INBOUND -i ${MACVLAN_IFACE} -j RETURN")
	inRedirectIdx := strings.Index(cmd, "-A PROXY_INBOUND -p tcp -j PROXY_IN_REDIRECT")
	require.NotEqual(t, -1, inboundIdx)
	require.NotEqual(t, -1, inRedirectIdx)
	require.Less(t, inboundIdx, inRedirectIdx)

	outboundIdx := strings.Index(cmd, "-A PROXY_OUTBOUND -o ${MACVLAN_IFACE} -j RETURN")
	multiportIdx := strings.Index(cmd, "-A PROXY_OUTBOUND -p tcp -m multiport")
	require.NotEqual(t, -1, outboundIdx)
	require.NotEqual(t, -1, multiportIdx)
	require.Less(t, outboundIdx, multiportIdx)

	noMacvlan := generateIptablesCommands(nil, false)
	require.NotContains(t, noMacvlan, "${MACVLAN_IFACE}")
}

func TestGetInitContainerSpec_MacvlanEnv(t *testing.T) {
	spec := GetInitContainerSpec(nil, true)
	require.Len(t, spec.Env, 2)
	require.Equal(t, "POD_IP", spec.Env[0].Name)
	require.Equal(t, "MACVLAN_IFACE", spec.Env[1].Name)
	require.Equal(t, defaultMacvlanIface, spec.Env[1].Value)

	specNoMacvlan := GetInitContainerSpec(nil, false)
	require.Len(t, specNoMacvlan.Env, 1)
	require.Equal(t, "POD_IP", specNoMacvlan.Env[0].Name)
}
