{{- $namespace := printf "%s" "os-system" -}}
{{ $lldap_rootpath := "/olares/userdata/dbdata" }}
{{- $lldap_secret := (lookup "v1" "Secret" $namespace "lldap-credentials") -}}
{{- $lldap_jwt_secret := "" -}}
{{- $lldap_ldap_user_pass := "" -}}
{{- $lldap_key_seed := "" -}}
{{ if $lldap_secret -}}
{{ $lldap_jwt_secret = (index $lldap_secret "data" "lldap-jwt-secret") }}
{{ $lldap_ldap_user_pass = (index $lldap_secret "data" "lldap-ldap-user-pass") }}
{{ $lldap_key_seed = (index $lldap_secret "data" "lldap-key-seed") }}
{{ else -}}
{{ $lldap_jwt_secret = randAlpha 64 | b64enc }}
{{ $lldap_ldap_user_pass = randAlpha 64 | b64enc }}
{{ $lldap_key_seed = randAlpha 64 | b64enc }}
{{- end -}}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    lldap: https://github.com/nitnelave/lldap
    k8s: https://github.com/Evantage-WS/lldap-kubernetes
  labels:
    app: lldap
    applications.app.bytetrade.io/author: bytetrade.io
  name: lldap
  namespace: os-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lldap
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        lldap: https://github.com/nitnelave/lldap
        k8s: https://github.com/Evantage-WS/lldap-kubernetes
      labels:
        app: lldap
    spec:
      containers:
        - env:
            - name: GID
              value: "1001"
            - name: LLDAP_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: lldap-credentials
                  key: lldap-jwt-secret
            - name: LLDAP_LDAP_BASE_DN
              valueFrom:
                secretKeyRef:
                  name: lldap-credentials
                  key: base-dn
            - name: LLDAP_LDAP_USER_DN
              valueFrom:
                secretKeyRef:
                  name: lldap-credentials
                  key: lldap-ldap-user-dn
            - name: LLDAP_LDAP_USER_PASS
              valueFrom:
                secretKeyRef:
                  name: lldap-credentials
                  key: lldap-ldap-user-pass
            - name: LLDAP_KEY_SEED
              valueFrom:
                secretKeyRef:
                  name: lldap-credentials
                  key: lldap-key-seed
            - name: LLDAP_DATABASE_URL
              value: "sqlite:///data/users.db?mode=rwc"
            - name: TZ
              value: CET
            - name: UID
              value: "1001"
            - name: LLDAP_KEY_FILE
              value: "/data/private_key"
            - name: RUST_BACKTRACE
              value: "full"
          image: beclab/lldap:0.0.1
          imagePullPolicy: IfNotPresent
          name: lldap
          ports:
            - containerPort: 3890
            - containerPort: 17170
          volumeMounts:
            - mountPath: /data
              name: lldap-data
      restartPolicy: Always
      volumes:
        - name: lldap-data
          hostPath:
            type: DirectoryOrCreate
            path: {{ $lldap_rootpath }}/lldap


---
apiVersion: v1
kind: Service
metadata:
  annotations:
    lldap: https://github.com/nitnelave/lldap
    k8s: https://github.com/Evantage-WS/lldap-kubernetes
  labels:
    app: lldap-service
  name: lldap-service
  namespace: os-system
spec:
  ports:
    - name: "3890"
      port: 3890
      targetPort: 3890
    - name: "17170"
      port: 17170
      targetPort: 17170
  selector:
    app: lldap
---
apiVersion: v1
data:
  base-dn: ZGM9ZXhhbXBsZSxkYz1jb20=
  lldap-jwt-secret: {{ $lldap_jwt_secret }}
  lldap-ldap-user-dn: YWRtaW4=
  lldap-ldap-user-pass: {{ $lldap_ldap_user_pass }}
  lldap-key-seed: {{ $lldap_key_seed }}
kind: Secret
metadata:
  name: lldap-credentials
  namespace: os-system
type: Opaque
