apiVersion: v1
kind: Service
metadata:
  name: nats
  namespace: user-system-{{ .Values.bfl.username }}
spec:
  type: ClusterIP
  selector:
    app: systemserver
  ports:
    - protocol: TCP
      name: nats
      port: 4222
      targetPort: 4222