name: Build and Upload WSL Ubuntu2204

on:
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v3

      - name: Install coscmd
        run: pip install coscmd        

      - name: Configure coscmd
        env:
          TENCENT_SECRET_ID: ${{ secrets.TENCENT_SECRET_ID }}
          TENCENT_SECRET_KEY: ${{ secrets.TENCENT_SECRET_KEY }}
          COS_BUCKET: ${{ secrets.COS_BUCKET }}
          COS_REGION: ${{ secrets.COS_REGION }}
          END_POINT: ${{ secrets.END_POINT }}
        run: |
          coscmd config -a $TENCENT_SECRET_ID \
                        -s $TENCENT_SECRET_KEY \
                        -b $COS_BUCKET \
                        -r $COS_REGION 

      # test
      - run: |
          bash build/build-ubuntu2204.sh