name: Build and Upload Redis

on:
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v3

      # test
      - env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
        run: |
          bash scripts/build-redis.sh linux/amd64

  push-arm64:
    runs-on: self-hosted

    steps:
      - name: Clean
        run: |
          sudo rm -rf redis*
          
      - name: "Checkout source code"
        uses: actions/checkout@v3

      - name: Install tools
        run: |
          sudo apt install -y make gcc

      # test
      - env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
        run: |
          sudo -E sh -c "bash scripts/build-redis.sh linux/arm64 && rm -rf redis*"
