name: Lint Check Charts

on:
  schedule:
    # This is a UTC time
    - cron: "30 1 * * *"
  workflow_dispatch:


jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
          
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.1

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.0
      
      - name: Pre package
        run: |
          bash scripts/package.sh

      - name: Run chart-testing (lint)
        run: |
          ct lint --chart-dirs \
          build/installer/wizard/config,build/installer/wizard/config/apps,,build/installer/wizard/config/gpu \
           --check-version-increment=false --all

