name: Push gpu-deps to S3

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Set OS: ubuntu-20.04, ubuntu-22.04'
        required: true


jobs:
  push:
    runs-on: ${{ github.event.inputs.environment }}
    steps:
    - name: 'Checkout source code'
      uses: actions/checkout@v3

    - env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'us-east-1'
      run: |
        bash scripts/upload-gpu-deps.sh
