name: Push images to S3

on:
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-22.04

    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v3

      # test
      - env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
        run: |
          bash build/image-manifest.sh && bash build/upload-images.sh .manifest/images.mf

  push-arm64:
    runs-on: [self-hosted, linux, ARM64]

    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v3

      - env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
        run: |
          export PATH=$PATH:/usr/local/bin:/home/ubuntu/.local/bin
          bash build/image-manifest.sh && bash build/upload-images.sh .manifest/images.mf linux/arm64
